### ISSUE TITLE
impossible de faire la mise à jour pour une commune

### ISSUE THREAD

**Issue by niconil** [osm-fr/bano#104]
il s'agit de la commune d'Ondes (code Insee 31403)
la mise à jour eéchoue avec le message : "Problème lors de la mise à jour"
sans plus de détail

cela se passe ici
http://cadastre.openstreetmap.fr/fantoir/#insee=31403&tab=0

**Comment by vdct** [comment]
Merci pour le signalement. En effet, il manque dans le cache BANO la totalité des fichiers du Cadastre, contrairement à ce qu'indique la page : "Cadastre récupéré le	15-09-2015 05:25:52" d'où le plantage.
La correction nécessite un accès aux serveurs du site cadastre.gouv.fr, actuellement indisponibles pour notre service de mise à jour. Du nouveau possible dans la semaine à venir.

**Comment by niconil** [comment]
Le message d'erreur pourrait-il être plus explicite, et indiquer de quelle manière signaler le pb. J'imagine qu'on ne va pas ouvrir un 'issue' github à chaque fois que les données cadastre d'une commune sont absentes.

**Comment by lhirlimann** [comment]
Y a toujours le problème :) c'est dommage le nombre de vois sur la commune devrait normelment diminué de maière significative.

**Comment by vdct** [comment]
Désolé pour la situation qui dure. C'est directement lié à la panne visible sur http://cadastre.openstreetmap.fr/ actuellement. On espère du mieux la semaine prochaine.

**Comment by cquest** [comment]
@vdct : Tu peux repasser cadastre.gouv.fr en "normal" :)

**Comment by vdct** [comment]
C'est reparti côté cadastre.openstreetmap.fr. Dans la foulée, problème résolu pour Ondes, je laisse @niconil vérifier pour clore le ticket.

**Comment by lhirlimann** [comment]
Vérifié.

**Comment by vdct** [comment]
Merci @lhirlimann
