### ISSUE TITLE
impossible de faire la mise à jour d'une commune

### ISSUE THREAD

**Issue by niconil** [osm-fr/bano#105]
bonjour

le problème rencontré il y a 15 jours pour la commune d'Ondes se répète avec la commune de Montjoire code INSEE : 31383
symptome : impossible de faire la mise à jour Bano

**Comment by vdct** [comment]
Même cause que pour Ondes, merci pour le signalement. (Vu que ça se répète il va falloir mesurer l'ampleur du phénomène)
En attendant j'ai forcé le rechargement du cadastre : 
=> http://cadastre.openstreetmap.fr/fantoir/#insee=31383&tab=0
Merci d'y jeter un oeil et de clore si tout est ok.

**Comment by niconil** [comment]
tu viens de renverser une bouteille d'encre rouge sur cette commune
(16 voies nouvelles non rapprochées !!)

**Comment by niconil** [comment]
la mise à jour fonctionne à nouveau our cette commune
