### ISSUE TITLE
Échec du rapprochement de toutes les maisons d'une rue avec numéro >= 10

### ISSUE THREAD

**Issue by bagage** [osm-fr/bano#107]
Voir ici : http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#18/45.04309/5.05563

Pour les maisons de 1 à 9 (sauf 2 bis, cf #45), le rapprochement se fait correctement.
Par contre dès le numéro 11, plus aucun rapprochement n'est fait.

**Comment by vdct** [comment]
L'orthographe récupérée du Cadastre ne permettait pas le rapprochement : les mots ST et Nicolas étaient collés.

**Comment by bagage** [comment]
Ça remarche, merci @vdct !

**Comment by niconil** [comment]
ok mais en faisant comme ça on met en place une rustine pour contourner un pb du cadastre
et du coup comme le rapprochement est fait aucune demande de correction sera faite au niveau du cadastre.
enfin c'est mon humble avis.

**Comment by vdct** [comment]
Pas tout à fait. Le problème n'existe pas côté serveurs du cadastre, c'est notre processus de récupération des données qui gère mal certains noms un peu longs. L'idéal serait de le corriger le + en amont possible, bien sûr, mais les cas sont rares et la correction en aval côté rapprochements est assez indolore.

**Comment by niconil** [comment]
avec ces explications je comprend  mieux
