### ISSUE TITLE
difficulte de rapprochement

### ISSUE THREAD

**Issue by niconil** [osm-fr/bano#109]
j'ai une voie qui ne se rapproche pas

pourtant tout semble bon
coté cadastre :
821340227X  VIEILLE RTE DE ST ETIENNE
(sauf que la voie est sans adresse)

coté JOSM
Vieille Route de Saint-Étienne

82134 code Insee de Nègrepelisse

Laurent

**Comment by vdct** [comment]
Il manuait des abréviations pour que le rapprochement se fasse.
Merci pour le signalement.
