### ISSUE TITLE
Échec de rapprochement 19 mars 1962 <-> DIX-NEUF mars 1962

### ISSUE THREAD

**Issue by bagage** [osm-fr/bano#110]
Dans au moins 2 communes, je remarque que le rapprochement ne se fait pas [dans ce cas (fantoir 260940006N)](http://cadastre.openstreetmap.fr/fantoir/#insee=26094&tab=0). Est-ce que c'est normal ? Si oui, y a quelque chose à faire ?

**Comment by vdct** [comment]
La correspondance manquait pour 19 <-> DIX NEUF
J'ai vérifié le cas donné en lien. Je te laisse vérifier l'autre et clore si ok

**Comment by bagage** [comment]
Je l'ai momentanément perdu de vue, mais je rouvrirai si ce n'est pas bon. Merci !
