### ISSUE TITLE
Échec détection de "Placa" au lieu de "Place"

### ISSUE THREAD

**Issue by bagage** [osm-fr/bano#112]
Sur [Manthes](http://cadastre.openstreetmap.fr/fantoir/#insee=26172&tab=0), toutes les places attendues en tant que "Placa" : 
* Placa de la Mairie
* Placa du Parc
* Placa de l'Église

Sur le cadastre, c'est bien marqué Place par contre visiblement.

**Comment by vdct** [comment]
Placa est bien identifié comme type possible :
https://github.com/osm-fr/bano/blob/master/dictionnaires/abrev_type_voie.txt#L223
mais son abréviation "PLA" est distincte de celle de Place ("PL"). Donc le rapprochement avec Placa d'un côté et Place de l'autre ne pourra pas se faire sans l'aide d'un tag ref:FR:FANTOIR.
