### ISSUE TITLE
processus de mise à jour qui n'aboutit pas

### ISSUE THREAD

**Issue by niconil** [osm-fr/bano#113]
A nouveau je tombe sur une commune où la mise à jour Bano laisse le voile grisé et ne rend pas la main
il s'agit de la commune de : Donzac (INSEE:82049)

cela me rappelle un cas similaire d'une commune au nord du 82

(ce n'est pas bloquant, je fais F5 au bout d'une minute pour reprendre la main)

Edit: la cas ne s'est pas reproduit à la mise à jour suivante (30 minutes après) donc je ne sais pas si cela vaut le coup d'investiguer....

**Comment by vdct** [comment]
Testé à l'instant, et ça passe tout seul. À réouvrir au cas où...
