### ISSUE TITLE
rapprochement non automatique

### ISSUE THREAD

**Issue by niconil** [osm-fr/bano#114]
(petit séjour vosgien - le secteur est plutôt clean coté adresse)
mais j'ai une voie qui ne se rapproche pas

pourtant tout semble bon
coté cadastre :
883830248T	RUE DU CHAMP RENARD

coté JOSM
Rue du Champ Renard

cela se passe ici :
http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#18/48.00752/6.61060

82134 code Insee de Nègrepelisse

Laurent

**Comment by vdct** [comment]
C'est à cause de cette relation : https://www.openstreetmap.org/relation/4110318 qui référence le Fantoir de la même rue, mais côté Saint-Étienne-lès-Remiremont. Le Fantoir de la relation prime, donc il empêche le rapprochement côté Remiremont.
En regardant le cadastre, Remiremont a une enclave au niveau de cette rue, et qui n'est pas dans OSM. Il faudrait d'abord corriger la limite administrative.
Ensuite pour ce qui est du rapprochement, en coupant la rue à la limite des 2 communes, et en ne référençant pas Saint-Étienne-lès-Remiremont dans la relation, chaque commune devrait bénéficier du rapprochement.

**Comment by niconil** [comment]
mais quel talent
je n'avais ni détecté l'enclave manquante ni la relation problématique

je ferme le ticket
