### ISSUE TITLE
lieux-dits discrets

### ISSUE THREAD

**Issue by niconil** [osm-fr/bano#116]
En m'interessant récemment à la commune de Basse-sur-le-Rupt (88037)

la page de rapprochement BANO est clean
c'est à dire 
0 voies avec adresses non rapprochées
0 voies sans adresses non rapprochées
0 lieux-dit non rapproché
(pour un total de 246 [26+8+212]  voies ou lieux dit rapprochés)

mais par curiosité je suis allé compter le nombre de ligne de l'export Fantoir Brut
j'en ai 250
1-il faudrait avoir un comptage des entrées FANTOIR por communes
2-je n'ai pas de moyen simple de voir quels sont les 4 codes et dénominations FANTOIR concernés

**Comment by vdct** [comment]
Il y en a en fait 5 non rapprochés, ce sont les 5 ayant une date d'annulation.
=> trier sur date_annul le tableau Fantoir pour les regrouper.
Indiquer quelles lignes du tableau correspondent à des rapprochements OSM est une bonne idée, je vais regarder ça.

**Comment by niconil** [comment]
encore un petit bug dans l'affichage de la page
http://cadastre.openstreetmap.fr/fantoir/liste_brute_fantoir.html

les colonnes de titres sont décalées
mais sinon le besoin est couvert

**Comment by niconil** [comment]
nickel
ok pour moi
