### ISSUE TITLE
doublons dans les données source=OSM et aussi lors de l'export

### ISSUE THREAD

**Issue by cquest** [osm-fr/bano#125]
Exemple: 693855530M-159... présent 19 fois avec comme source OSM...

**Comment by vdct** [comment]
Lors de l'étape d'insertion des données ("cumul"), on n'a aucun doublon. Ils sont produits via les updates en préparation des exports.
Les adresses en cause sont de format xxx-yy (avec un trait d'union) et je suppose que les updates tronquent avant le trait d'union, sûrement pour une bonne raison dans certains cas.
La zone en cause sur ton exemple : 
http://www.openstreetmap.org/way/4998506#map=19/45.74790/4.78223

**Comment by cquest** [comment]
Ouille, le méchant effet de bord avec ces numéros franchement exotiques... je regarde comment éviter ça, en testant que le premier nombre est inférieur au second ?

**Comment by vdct** [comment]
Pourquoi une telle règle ? Sur l'exemple ci-dessus c'est le contraire : 171 > 16 dans 171-16 par exemple. Mais comme le second nombre ressemble plus à un numéro d'ordre, on ne peut pas garantir qu'il sera inférieur ou supérieur au 1er, qui dépend plus d'une séquence de numéros dans la rue. En gros je ne vois pas de logique qui lie les nombres de par d'autre du '-'.
Si le test se contente de vérifier que : 
- à gauche du '-' c'est un numéro qu'on tolèrerait comme n° d'adresse
- à droite du '-' c'est un entier
alors on valide l'adresse.

**Comment by cquest** [comment]
Je sais, c'est imparfait comme traitement, mais difficile de traiter le manque d'homogénéïté sur les addr:housenumber 

Les cas rencontrés avec les tirets ont la forme:
12-16 voire 3-5-7 : donc sûrement 12,14,16 et 3,5,7 (cas relativement fréquent, 272 rien que sur le 69)
12-A : le A est un complément
159-16 : le 16 est un complément... mais oui on peut confondre avec le premier cas

Dans le premier cas, il est souhaitable de les séparer en n numéros, le 12 et le 16 ou 3, 5 et 7
Dans les autres cas, les garder tel quel...

Autre solution, modifier la requête de "séparation" pour qu'elle ne crée pas de doublon si un numéro identique existe déjà...
