### ISSUE TITLE
entree inconnue du dictionnaire

### ISSUE THREAD

**Issue by niconil** [osm-fr/bano#129]
Bonjour,

toujours en train de parcourir le Tarn ...
je suis tombé sur cela

810920013A	VC HAM LDT D EN CAZAREL	--

que faudrait-il ?
2 entrées dans le dictionnaire pour
que VC HAM soit reconnu comme HAM
que LDT soit tranformé en LIEU-DIT
(enfin ce n'est qu'une suggestion)

en attendant dans osm j'ai mis
name= Hameau Lieu-dit d'en Cazarel
ref:FR:FANTOIR= 810920013A

cela se passe ici
http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#18/43.69942/1.91078

**Comment by cquest** [comment]
"Hameau d'en Cazarel" me semble plus exact... lieu-dit ne fait pas partie du nom, tout comme "Chemin dit de la Tour" -> "Chemin de la Tour"

**Comment by niconil** [comment]
bien noté chef :-)

**Comment by vdct** [comment]
Sur tout FANTOIR cette voie est la seule avec un libellé de voie incluant 'HAM LDT', donc en effet plutôt qu'en faire une règle dans le code, ajouter le ref:FR:FANTOIR dans la donnée est bienvenu :)
