### ISSUE TITLE
Erreur de décodage pour "RUE A DE ST EXUPERY" 

### ISSUE THREAD

**Issue by bagage** [osm-fr/bano#136]
La rue `RUE A DE ST EXUPERY` est détectée par BANO comme `Rue à de Saint-Exupéry` au lieu de `Rue Antoine de Saint-Exupéry`. Code fantoir 840070375D.

Cf ici : http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#18/43.9311536179/4.84528269945

**Comment by bagage** [comment]
Aussi `RUE F DE R DE LA VALFENIERE` correspond à `François de Royers de la Valfenière` (cf http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#19/43.93515/4.80494). Qu'est-ce qu'il faut faire dans ce cas ? Forcer le FANTOIR ou c'est quelque chose qui doit être corrigé dans BANO ?

**Comment by vdct** [comment]
Je viens de forcer les FANTOIR pour ces 2 rues dans OSM. C'est hasardeux de tenter un rapprochement sur un prénom d'un côté et son initiale de l'autre. L'ajout du code FANTOIR dans OSM est typiquement là pour compenser.
C'est visible ici : https://dev.cadastre.openstreetmap.fr/fantoir/#insee=84007&tab=1

Déso pour la réponse.... tardive :/
