### ISSUE TITLE
Voies qui apparaisent dans plusieures colonnes

### ISSUE THREAD

**Issue by JeaRRo** [osm-fr/bano#144]
Sur la communes de Nattages dans l'Ain ( 01271) il  y a quatre voies dans la colonne : http://cadastre.openstreetmap.fr/fantoir/#insee=01271&tab=0 donc AVEC adresse sans rapprochement 

mais elles sont aussi dans http://cadastre.openstreetmap.fr/fantoir/#insee=01271&tab=3
donc SANS adresse avec rapprochement...

??

**Comment by vdct** [comment]
Problème corrigé par la nouvelle version de BANO consultable ici : http://dev.cadastre.openstreetmap.fr/fantoir/#insee=01286
