### ISSUE TITLE
Rapprochement des surfaces en highway=pedestrian

### ISSUE THREAD

**Issue by vdct** [osm-fr/bano#154]
Elles semblent absentes en v2, cf https://lists.openstreetmap.org/pipermail/talk-fr/2019-November/094874.html

**Comment by gendy54** [comment]
J'ai oublié de préciser: que ces voies là soient sous _way_ ou sous _relation_

**Comment by vdct** [comment]
@gendy54 tu as des exemples de voies, que je sache quoi chercher ?

**Comment by gendy54** [comment]
https://www.openstreetmap.org/way/303333171
https://www.openstreetmap.org/way/303333172

**Comment by vdct** [comment]
Merci mais comme ceux là tu les as corrigés c'est pas les plus pratiques pour trouver le bug :)
Si tu tombes sur d'autres tu les indiques ici sans y toucher trop vite, que j'ai le temps de regarder ?

**Comment by gendy54** [comment]
Oups ;)
Bien chef!

**Comment by don-vip** [comment]
Exemples à Toulouse:
 * 315558325K | PL STEPHANE HESSEL | https://www.openstreetmap.org/way/604247154
 * 315556857P | ALL PIERRE BERTAUX | https://www.openstreetmap.org/way/495231481

**Comment by don-vip** [comment]
Je valide le fix :)
