### ISSUE TITLE
Rapprochement voie avec majuscule accentuée

### ISSUE THREAD

**Issue by lmagreault** [osm-fr/bano#156]
Sur la commune de Pont-de-Poitte (39435), il existe une voie FANTOIR sans adresse numérotée "CHEM DE L'EPINEY" pour laquelle de le rapprochement ne semble pas se faire avec la voie OSM "Chemin de l'Épinay".
Problème liée à la majuscule accentuée ?

**Comment by vdct** [comment]
Les accents sont gérés, par exemple ici :
http://dev.cadastre.openstreetmap.fr/fantoir/#insee=92047&tab=1 avec l'Avenue Étienne de Montgolfier.
Le souci pour Pont-de-Poitte serait plutôt sur la divergence d'orthographe entre EpinAy et EpinEy. Si la bonne orthographe est celle d'OSM, avec un 'a', alors le rapprochement peut être forcé en ajoutant le code FANTOIR sur les ways highway=* concernés.

**Comment by lmagreault** [comment]
Bien vu. J'étais focalisé sur l'accent. Merci.
