### ISSUE TITLE
Prise en compte des lettres accentuées spécifiques aux langues régionales 

### ISSUE THREAD

**Issue by ray66** [osm-fr/bano#157]
Pour comparer les noms OSM aux noms FANTOIR, les outils Bano ignorent les accents présents dans la langue française. Dans les Pyrénées Orientales, beaucoup de rues et lieux ont des noms en catalan qui contiennent des lettres accentuées non présentes dans la langue française. Dans ces cas, les rues et lieux OSM ne sont pas rapprochées. Exemple : 

    FANTOIR : 662255000S    CAMI DE LA MUNTANYA
    OSM :     way 561952329 Camí de la Muntanya 

Je propose d'ignorer les accents des lettres 

    í ò ó ú Í Ò Ó Ú
lors du rapprochement avec Fantoir et le cadastre.

**Comment by vdct** [comment]
@ray66 j'ai vérifié sur quelques cas, ça semble fonctionner.
Ton retour bienvenu, merci

**Comment by ray66** [comment]
@vdct : Je confirme pour les lettre í, ó, ò et ù, pas d’occurrence pour les majuscules. Merci.
