### ISSUE TITLE
Pourquoi avoir choisi du gris alors que l'idée sous-jacente est bien de dégommer du rouge non ?

### ISSUE THREAD

**Issue by vinber** [osm-fr/bano#165]

**Comment by vdct** [comment]
Tu peux en dire plus un peu ? :)

**Comment by vinber** [comment]
pardon, pas explicite...

dans l'affichage banov2, quand il n'y a pas de rapprochement entre fantoir et osm, c'est gris, or il me semble si j'ai tout compris que ceux sont ces rues qu'il s'agit de dégommer.

quand le rapprochement existe, c'est vert.

(je ne sais pas envoyer les captures d'écran depuis le téléphone, cela viendra plus tard)

**Comment by vdct** [comment]
Le gris a plusieurs significations, je te renvoie à la légende du fond de carte :
https://wiki.openstreetmap.org/wiki/FR:France/WikiProject_Base_Adresses_Nationale_Ouverte_(BANO)#L.C3.A9gende

**Comment by vinber** [comment]
Ok, j'avoue que je n'avais pas fait le distingo fantoir-cadastre pour le rouge. Dans ma tête le rouge est dédié aux "trucs" à dégommer, que cela soit cadstre, fantoir, mais en gros tout ce qui peut améliorer OSM.
Je ferme donc

**Comment by vinber** [comment]
ok, je me suis trompé en plus de dépot. Cela concernait également https://dev.cadastre.openstreetmap.fr/fantoir/
