### ISSUE TITLE
Rapprochement des passages abréviés PASS

### ISSUE THREAD

**Issue by don-vip** [osm-fr/bano#167]
Non rapprochés:
315550335A | PASS ANDRE CHAUBET | https://www.openstreetmap.org/way/229329469 | name=Passage André Chaubet
315550334Z | PASS ANDRE GASTOU | https://www.openstreetmap.org/way/261688208 | name=Passage André Gastou

Actuellement "PASS" est rapproché avec "PASSE" et jamais avec "PASSAGE".

**Comment by vdct** [comment]
Ca devrait mieux se "passer" désormais.

**Comment by don-vip** [comment]
Effectivement :) 

![image](https://user-images.githubusercontent.com/596867/74773040-69623200-5291-11ea-9cf7-9a762efe3d20.png)
