### ISSUE TITLE
 Rapprochement des passerelles abréviées PAS

### ISSUE THREAD

**Issue by don-vip** [osm-fr/bano#171]
Non rapproché:
315558361Z | PAS DE TABAR | https://www.openstreetmap.org/way/30252535 | name=Passerelle de Tabar

**Comment by vdct** [comment]
Impossible à corriger dans le code car ça revient à interpréter l'abréviation PAS (pour 'passage') comme PLE (comme 'Passerelle'). C'est un bug de données, au moins contraire à ce qui est documenté dans FANTOIR (https://data.economie.gouv.fr/api/datasets/1.0/fichier-fantoir-des-voies-et-lieux-dits/attachments/descriptif_du_fichier_national_fantoir_pdf). Le contournement pour forcer le rapprochement consiste à saisir le code FANTOIR sur le way concerné :/

**Comment by don-vip** [comment]
OK merci, j'ai ajouté le code: https://www.openstreetmap.org/changeset/81348677

**Comment by don-vip** [comment]
ça fonctionne, merci :)
