### ISSUE TITLE
Dans la colonne 2, d'où vient le nom OSM

### ISSUE THREAD

**Issue by vinber** [osm-fr/bano#175]
Bonjour,
sur Ascain (pays Basque) (https://dev.cadastre.openstreetmap.fr/fantoir/#insee=64065&tab=1).

RUE OLETAKO BIDEA | Rue Oletako Bidea sont rapprochées et dans la relation il est proposé comme nom Rue Oletako Bidea.

Dans les données OSM, c'est Oletako Bidea (bidea voulant dire rue en basque).
Pourquoi la relation propose Rue Oletako Bidea ?

Est-ce le bon endroit pour ces questions ?

**Comment by vdct** [comment]
Oui c'est le bon endroit ;)
Le rapprochement ne peut pas se faire avec RUE OLETAKO BIDEA côté FANTOIR et juste "Oletako Bidea" côté OSM, sans "Rue".
Si ça colle ici c'est grâce aux points d'adresse comme https://www.openstreetmap.org/node/7124070777 qui ont addr:street=Rue Oletako Bidea

**Comment by vinber** [comment]
oui mais justement le débat va démarrer sur quel est le nom !!! mettre Route Olétako Bidea, c'est un peu comme écrire tout le panneau bilingue Route Olétako d'une part et Olétako Bidea d'autre part ! Et comme il n'y a pas beaucoup de panneaux !!!
J'essaie de récupérer les données de la mairie, on va voir !

**Comment by vdct** [comment]
Moi tu me demandes d'où vient le nom, je te réponds sur d'où vient le nom :p :p :p 
Le rapprochement se fait sur la similitude d'orthographe *ou* via la présence d'un code FANTOIR. Si on estime que le nom doit être dans OSM "Olétako Bidea" alors le rapprochement se fera en ajoutant le bon code Fantoir sur les objets

**Comment by vinber** [comment]
oui, pardon ce n'était pas pour lancer le débat ici :) mais j'anticipais ce qui allait arriver entre l'office de tourisme, la mairie, la comcom, les habitants, les contributeurs bbasque, franco !
Et oui j'allais justement avancer sur le fait de rajouter le fantoir pour que la rapprochement ait lieu "indépendamment" du nom.
Ne serait-il cependant pas plus OSM compatible que le nom dans la relation créée soit le nom OSM de la rue (même si j'ai bien compris que le rapprochement ici se fait avec les addr:street=)?
Merci encore :)

**Comment by vdct** [comment]
Oui ce serait bien d'avoir un même nom à tous les endroits : sur le tag name des highways, sur le tag name de la relation associatedStreet, et sur les (éventuels) tags addr:street un peu doublons qu'on trouvera sur des POIs

**Comment by vinber** [comment]
le doublon des tags addr:street, avec iD qui met tellement en avant le fait de renseigner c'est "normal" et sans doute utile dans pas mal de temps pour remonter ce type d'adresse (au passage il y a un super fonction dans idée qui permet de supprimer tous les tag ne concernant pas l'adresse mais c'est pas le sujet ici plutôt une demande à faire pour josm :) )

**Comment by vinber** [comment]
je ferme à priori
