### ISSUE TITLE
Que la ref fantoir, sans les numéros de rue

### ISSUE THREAD

**Issue by vinber** [osm-fr/bano#176]
Avant d'avancer sur les numéros de rue et le bon nom de rue (franco-basque), je me dis que j'aimerai d'abord vérifier que c'est "cohérent" entre les diverses sources, et pour cela rajouter la ref:fantoir pour que les rapprochements se fassent.

faire une relation associatedstreet "juste" avec la ref:FR fantoir et le way correspondant c'est mieux que de mettre seulement la ref sur le way ?

**Comment by vdct** [comment]
La relation c'est uniquement si tu as aussi des adresses à inclure dedans avec le rôle house. Sinon ça ne sert à rien de se compliquer, la ref sur le way suffit pour les rapprochements.
(pas sûr que ce soit le bon endroit pour discuter de tout ça ceci dit...)

**Comment by vinber** [comment]
ok merci :)
