### ISSUE TITLE
Non-rapprochement énigmatique

### ISSUE THREAD

**Issue by don-vip** [osm-fr/bano#177]
315551788E | RUE CAUSSADE

Et pourtant:
- https://www.openstreetmap.org/relation/1908859 | type=associatedStreet | name=Rue Caussade
- https://www.openstreetmap.org/way/22390505 | highway=residential | name=Rue Caussade
- https://www.openstreetmap.org/way/208439016 | highway=residential | name=Rue Caussade

**Comment by vdct** [comment]
Dans FANTOIR on a une rue DE LE CAUSSADE (315551789F) et une rue CAUSSADE. Dans BANO le rapprochement se fait sur la première au détriment de la seconde. Est-ce qu'il y a 2 rues différentes dans la commune avec des noms aussi proches ?

**Comment by don-vip** [comment]
OK je comprends mieux. Il y a à [l'Union](https://dev.cadastre.openstreetmap.fr/fantoir/liste_brute_fantoir.html#insee=31561) (commune au nord de Toulouse) une "impasse de la Caussade" (315610122T, https://www.openstreetmap.org/way/33578985). Souci: le début de cette impasse commence sur la commune de Toulouse:

![image](https://user-images.githubusercontent.com/596867/74383460-86a98300-4def-11ea-8245-781b2d207c45.png)

Dans FANTOIR et les données open data de Toulouse, 315551789F est effectivement un petit tronçon dénommé "Rue de la Caussade". Rien à voir avec la Rue Caussade qui est en plein centre-ville. Idéalement c'est ce tronçon qui devrait être remonté comme non rapproché.

**Comment by don-vip** [comment]
J'ai ajouté des REF:FR:FANTOIR sur les voies, j'espère que ça va corriger le souci:
https://www.openstreetmap.org/changeset/81187597

**Comment by vdct** [comment]
Ok, situation pas cool pour l'adressage, et pas gérée par BANO, où les mots de liaison sont supprimés en préparation des rapprochements : https://github.com/osm-fr/bano/blob/packaging/bano/constants.py#L45
Par suite une rue CAUSSADE et une rue DE LA CAUSSADE sont comme fusionnées pour BANO. Il y a cependant un levier en tenant compte du code FANTOIR associé. Pour l'instant je privilégie le code issu de FANTOIR sur celui issu d'OSM, c'est historique et à la réflexion je ne vois pas l'intérêt, je tente un correctif qui consiste à privilégier le code FANTOIR issu d'OSM sur celui issu de FANTOIR

**Comment by don-vip** [comment]
Visiblement ça marche :) merci !
