### ISSUE TITLE
Fantoir 2020

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/bano#179]
Hello,

Celui de janvier semble montrer le bout de son nez ici  https://data.economie.gouv.fr/api/datasets/1.0/fichier-fantoir-des-voies-et-lieux-dits/attachments/fichier_national_fantoir_situation_janvier_2020_zip/ 

#HTH

**Comment by vdct** [comment]
Merci @deuzeffe :)
Chargement en cours...

**Comment by vdct** [comment]
Chargement effectué. Les voies les plus récentes dans les données FANTOIR sont du 27 janvier 2020
