### ISSUE TITLE
Rapprochement des caractères accentués

### ISSUE THREAD

**Issue by don-vip** [osm-fr/bano#180]
Non-rapproché:
315551834E | 2018-10-22 | RUE CESARIA EVORA | https://www.openstreetmap.org/way/513011491 | name=Rue Cesária Évora

**Comment by vdct** [comment]
Cárambá, encore ráté :)

**Comment by don-vip** [comment]
Fix confirmé :) 

![image](https://user-images.githubusercontent.com/596867/74772822-040e4100-5291-11ea-946b-073339080a59.png)
