### ISSUE TITLE
Intégrer le produit Adresses d'Etalab

### ISSUE THREAD

**Issue by vdct** [osm-fr/bano#188]
Les fichiers : https://adresse.data.gouv.fr/data/ban/adresses/latest/csv/
A priori en substitution des entrées Cadastre et BAL Locales

**Comment by deuzeffe** [comment]
Hello,

Bravo pour le boulot !!!

Question bête : il y a des en-têtes de colonne dans les csv de la base Adresses mais pas dans les csv de BANO v.2. C'est normal ? Ou c'est moi qui n'y pige que pouic ?

Merci pour ta réponse, quelle qu'elle soit.

**Comment by vdct** [comment]
Merci :)
Y a pas trop de rapport entre les deux CSV, le lien pour BANO v2 c'est plutôt avec les fichiers de BANO v1 qui n'ont pas d'en-tête non plus. Tu peux les voir ici : http://previous.bano.openstreetmap.fr/data/

**Comment by deuzeffe** [comment]
Merci pour ta réponse.

J'avoue n'avoir jamais utilisé les csv BANO v1, du moins volontairement et consciemment :) Je tapais directement dans les csv de la défunte BAN odbl.

Maintenant, je tape dans Adresses, donc. Essentiellement pour surveiller l'évolution de la remontée des données terrains transmises par ma commune. Je peux te dire que ce n'est pas rapide. Du tout. 
Et je ne sais pas qui alerter (à part ma commune, mais elle a autre chose à faire en ce moment).

Vais peut-être m'amuser à comparer les données BANO v2 et les données Adresses, même si dans le csv BANO, la source est mentionnée.

**Comment by deuzeffe** [comment]
@vdct on clôt ?

**Comment by vdct** [comment]
@deuzeffe ah oui oui :)
