### ISSUE TITLE
Bascule BANO -> BANO v2

### ISSUE THREAD

**Issue by vdct** [osm-fr/bano#189]
Récapitulatif des actions....
- [X] configurer le proxy sur osm11 pour la bascule de bano.openstreetmap.fr
- [x] bascule de https://bano.openstreetmap.fr (osm104) en https://prev.bano.openstreetmap.fr
- [x] faire pointer https://bano.openstreetmap.fr sur osm162 (racine à /data/project/bano.openstreetmap.fr/web)
- [ ] redirection permanente de https://dev.cadastre.openstreetmap.fr vers https://bano.openstreetmap.fr/contribuer (page 'fantoir' et pages associées)
- [ ] ne pas toucher au DNS de cadastre.openstreetmap.fr mais ajouter une popup pour indiquer que c'est une version plus à jour en code ni en données, et proposer le lien vers bano.openstreetmap.fr
- [ ] bascule du rendu carto BANO sur osm162
- [ ] mise à jour du wiki pour les différents liens
- [x] page à créer pour la HOME de https://bano.openstreetmap.fr

********* ci-dessous la proposition initiale pour archive **************
- [ ] bascule de https://bano.openstreetmap.fr (osm104) en https://prev.bano.openstreetmap.fr
- [ ] faire pointer https://bano.openstreetmap.fr sur osm162 /data/project/bano.openstreetmap.fr
- [ ] bascule de https://cadastre.openstreetmap.fr (osm104) en https://prev.cadastre.openstreetmap.fr
- [ ] faire pointer https://cadastre.openstreetmap.fr sur osm162 (actuel https://dev.cadastre.openstreetmap.fr)
- [ ] redirection permanente https://dev.cadastre.openstreetmap.fr vers https://cadastre.openstreetmap.fr
- [ ] page d'arrivée sur le futur https://cadastre.openstreetmap.fr + lien vers https://prev.cadastre.openstreetmap.fr et liens vers les alternatives aux services de https://prev.cadastre.openstreetmap.fr
- [ ] bascule du rendu carto BANO sur osm162
- [ ] mise à jour du wiki pour les différents liens

**Comment by Bibi56** [comment]
`prev`=previous ou preview.
Je préfère donc être explicite (`previous` ou `old`).

**Comment by vdct** [comment]
Merci @Bibi56 
Je pensais au même 'prev' que pour le site : prev.openstreetmap.fr
mais previous est bien aussi

**Comment by jocelynj** [comment]
Je viens de créer sur gandi previous.bano.openstreetmap.fr -> osm104

**Comment by vdct** [comment]
@jocelynj merci
en // je mettais à jour le ticket, donc previous.cadastre.openstreetmap.fr ne devrait pas être nécessaire

**Comment by amatissart** [comment]
Je constate que pour certains départements les .csv de BANO v2 semblent incomplets.

Exemple:
https://previous.bano.openstreetmap.fr/data/bano-49.csv : 247795 adresses
https://bano.openstreetmap.fr/data/bano-49.csv : 3777 adresses, toutes dans des communes commençant par A.

De même des communes sont manquantes dans [bano-71.csv](https://bano.openstreetmap.fr/data/bano-71.csv), [bano-90.csv](https://bano.openstreetmap.fr/data/bano-90.csv), [bano-62.csv](https://bano.openstreetmap.fr/data/bano-62.csv), etc.
Il n'y aurait pas eu un problème lors de l'export des fichiers .csv ?

**Comment by vdct** [comment]
@amatissart merci du signalement. Je regarde ça

**Comment by vdct** [comment]
@amatissart j'ai apporté des corrections qui devraient être effectives dans les exports datés du 10 mai.

**Comment by amatissart** [comment]
@vdct Merci ! À quelle fréquence sont mis à jour les exports ?  
Les fichiers visibles sur https://bano.openstreetmap.fr/data/ datent toujours du 8 mai.

**Comment by vdct** [comment]
@amatissart Merci pour ce signalement bis :)
Les exports du 11 sont en train d'arriver, une histoire de quelques minutes

Les exports sont quotidiens, durant la nuit. Début du process à 2h du matin heure de Paris. Leur heure de dispo est fonction du volume de mises à jours faites dans BANO dans les 24h qui précèdent.

**Comment by jocelynj** [comment]
@vdct : Est-ce qu'il reste encore des trucs à faire dans la config ?

**Comment by vdct** [comment]
@jocelynj les cases non cochées en haut. Mais on pourra les traiter séparément. Là le service tourne, avec ce qui a déjà été fait. Je vais clore ce ticket
