### ISSUE TITLE
 Exports json : les fichiers ne sont pas valides 

### ISSUE THREAD

**Issue by mk1990-med** [osm-fr/bano#191]
Les fichiers exports Json par département (disponible sur http://bano.openstreetmap.fr/data/) ne sont pas valides.

**Comment by vdct** [comment]
@mk1990-med  merci pour le signalement. J'ai procédé à une correction dont l'effet devrait être visible dans les fichiers datés du 13 mai, disponibles demain en matinée

**Comment by mk1990-med** [comment]
Merci pour votre réactivité. En testant les nouveaux fichiers, je suis tombé sur quelques anomalies :

ligne :  10935  fichier :  ./out/bano-33.json  erreur:  Expecting ',' delimiter: line 1 column 89 (char 88)
ligne :  24864  fichier :  ./out/bano-62.json  erreur:  Expecting ',' delimiter: line 1 column 69 (char 68)
ligne :  10530  fichier :  ./out/bano-56.json  erreur:  Invalid control character at: line 1 column 86 (char 8
ligne :  6819  fichier :  ./out/bano-32.json  erreur:  Expecting ',' delimiter: line 1 column 94 (char 93)
ligne :  5486  fichier :  ./out/bano-91.json  erreur:  Expecting ',' delimiter: line 1 column 73 (char 72)
ligne :  4075  fichier :  ./out/bano-39.json  erreur:  Invalid \escape: line 1 column 789 (char 788)
ligne :  16145  fichier :  ./out/bano-85.json  erreur:  Expecting ',' delimiter: line 1 column 74 (char 73)
ligne :  20023  fichier :  ./out/bano-29.json  erreur:  Invalid control character at: line 1 column 72 (char 71)
ligne :  10494  fichier :  ./out/bano-67.json  erreur:  Expecting ',' delimiter: line 1 column 87 (char 86)
ligne :  8234  fichier :  ./out/bano-63.json  erreur:  Expecting ',' delimiter: line 1 column 72 (char 71)
ligne :  2104  fichier :  ./out/bano-19.json  erreur:  Expecting ',' delimiter: line 1 column 88 (char 87)

**Comment by vdct** [comment]
Merci pour ces précisions sur les anomalies, ça va me permettre une révision plus poussée

**Comment by vdct** [comment]
@mk1990-med les fichiers produits à partir de demain 16/05 devraient être conformes. Le commit ci-dessus apporte plusieurs correctifs. Merci pour vos retours éventuels

**Comment by vdct** [comment]
Pas de nouvelles => clos
