### ISSUE TITLE
Cas d'une voie dont le rapprochement ne se fait pas

### ISSUE THREAD

**Issue by niconil** [osm-fr/bano#192]
Bonjour,

pour la commune de Saint-Antonin-Noble-Val (82155)
j'ai le cas d'une place dont le rapprochement ne se fait pas
Place Ramon Jordan
elle est saisie comme relation, il y a bien la Ref fantoir (821550315B)
mais cette dernière rue résiste
elle n'apparait pas non plus dans les autres onglets 

peut être un problème de mon coté mais je ne vois pas, alors j'ouvre ce ticket

**Comment by vdct** [comment]
@niconil  merci pour le signalement :)
La cause était une désynchronisation de la base OSM locale qui alimente BANO. C'est rétabli.
