### ISSUE TITLE
FANTOIR 04/20

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/bano#193]
Hello,

Le FANTOIR d'avril 2020 est bien entendu sorti. @vdct, tu l'as récupéré ?

++

**Comment by vdct** [comment]
Fait à l'instant, merci @deuzeffe :)

**Comment by vdct** [comment]
clos par https://github.com/osm-fr/bano/commit/f89fe5e2a6c34fbba3b492e00fd2b5a8aa0df0d9

**Comment by deuzeffe** [comment]
Damnède, je ne l'avais pas signalé dans le bon dépôt : toutes mes confuses :|
