### ISSUE TITLE
Inversion lat lon suite à Bano v2

### ISSUE THREAD

**Issue by Barbaro** [osm-fr/bano#194]
Bonjour à tous,

Je ne sais pas si je suis au bon endroit, mais je ne sais pas trop où poster le cas échéant pour être honnête, donc je m'excuse en avance si je me suis perdu.

Il semblerait que depuis les dernières mises à jour du référentiel (le soucis remonte maintenant à environ 1 mois max), des adresses voient leur lat et lon inversés. Le problème se pose dans le fichier http://bano.openstreetmap.fr/data/full.sjson.gz mais pas dans le fichier csv du département concerné.

Par exemple, pour l'adresse 17 Rue clemenceau 29400 Landivisiau j'obtiens le résultat suivant dans addok :
![image](https://user-images.githubusercontent.com/1368313/84039671-de24bd80-a9a1-11ea-815e-ae8239915347.png)

Le problème n'est pas présent dans le fichier https://previous.bano.openstreetmap.fr/data/full.sjson.gz sur cet exemple là. Le nouveau process pourrait-il être à l'origine de ce soucis ?

Je ne sais pas combien d'adresses sont concernées pour être honnête, même si cela ne concerne à priori qu'une infime partie d'entre elles.

Merci pour vos retours.

**Comment by vdct** [comment]
Bonsoir,
Merci pour le signalement. J'identifie le problème sur d'autres communes, mais je n 'ai pas encore compris comment il surgit, ça semble affecter un faible nombre de voies à chaque fois. Je vais avoir besoin d'un peu de temps pour investiguer.

**Comment by vdct** [comment]
@Barbaro la correction apportée ce soir devrait traiter le souci. Ce sera effectif dans les exports publiés demain matin. Merci pour votre retour en cas de problème.

**Comment by Barbaro** [comment]
Le problème semble résolu, merci pour la réactivité !
