### ISSUE TITLE
BANO: l'export des json est cassé, ils sont vides

### ISSUE THREAD

**Issue by cquest** [osm-fr/bano#198]
http://bano.openstreetmap.fr/data/

**Comment by cquest** [comment]
Un premier transfert d'issue ça se fête ? (je ne savais même pas que ça existait)
Dispo si besoin d'un coup de main

**Comment by vdct** [comment]
Une table utilisée dans les exports JSON était vide, par ricochet elle vidait tout le contenu des exports. 
Elle est regénérée chaque nuit, je n'explique pas comment elle s'est retrouvée vide. 
Aujourd'hui les exports sont ok. A surveiller, et il y a matière à rendre le process plus robuste en n'effaçant pas les fichiers de la veille si ceux du jour sont vides ou même plus petits de quelques %...

**Comment by vdct** [comment]
Ca ne semble pas s'être reproduit. Clôture
