### ISSUE TITLE
Fantoir estival 2020

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/bano#200]
Hello, 

Le FANTOIR 07/20 est arrivé \o/ ici : https://www.data.gouv.fr/fr/datasets/r/8000e9e0-fd6a-4c27-8a19-0a89dbeb6258

@vdct, à toi de jouer ;)
(fais gaffe : le fichier décompressé est nommé FANTOIR0620)

**Comment by vdct** [comment]
Merci @deuzeffe pour la veille :)
Je m'en occupe dimanche, je suis loin de mon PC d'ici là

**Comment by deuzeffe** [comment]
Pas d'urgence, hein ;) Profite bien de ce qu'il te reste de jours de congés !

**Comment by vdct** [comment]
Fermé avec https://github.com/osm-fr/bano/commit/e7a247c6aed6f7fc57887ef1093dd0df850690c1
Merci @deuzeffe  :)
