### ISSUE TITLE
Ajout d'une licence libre?

### ISSUE THREAD

**Issue by bzg** [osm-fr/bano#203]
Je me dis que ça serait cohérent avec le reste des démarches OSM et pourrait peut-être faciliter des contributions « de passage » - même si je doute qu'il y en ait beaucoup... une MIT me paraîtrait appropriée.

**Comment by tuxayo** [comment]
Et surtout pour la réutilisation dans d'autres pays il y a sûrement une partie des outils qui peuvent servir.

Pour la licence je pensais à une AGPL pour que les modifs que quelqu'un fais pour un pays puissent aussi servir aux autres. Mais ça semble être un ensemble d'outils et pas une application avec la partie front-end web donc quelque soit la licence pas de copyleft qui arrivera a atteindre les personnes utilisatrices. Donc ouais MIT ou n'importe quelle licence, au fond ça ne devrait rien changer (de ce que je comprends ^^)

**Comment by bzg** [comment]
Oui, une licence libre, ce serait bien, quelle qu'elle soit.

**Comment by vinber** [comment]
- [ ] Définir MIT ou AGPL 

- [ ] Faire une proposition de licence avec le doc qui va bien

**Comment by vdct** [comment]
Merci pour vos suggestions. J'ai fait simple.
