### ISSUE TITLE
Format des CPs multiples dans l'export JSON

### ISSUE THREAD

**Issue by vdct** [osm-fr/bano#206]
Par exemple : "89110;89710" au lieu de ["
89110","89710"]

**Comment by vdct** [comment]
Extrait des exports du jour :
{"id":"89411B229D","citycode":"89411","type":"place","name":"Sous les Hameaux",**"postcode":["89190", "89320"]**,"lat":"48.163598","lon":"3.500475","city":"Les Vallées de la Vanne","departement":"Yonne","region":"Bourgogne-Franche-Comté","importance":0.05}
@cquest je te laisse faire un retour après import Addok ?

**Comment by cquest** [comment]
C'est tout bon !
