### ISSUE TITLE
Fantoir d'automne confiné 2020

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/bano#207]
Hello, 

Le Fantoir nouveau est arrivé ! (le Beaujolais de même facture attendra un peu :P)

Il est là : https://data.economie.gouv.fr/api/datasets/1.0/fichier-fantoir-des-voies-et-lieux-dits/attachments/fichier_national_fantoir_situation_novembre_2020_zip/ (pas encore regardé le ventre de la bête.)

@vdct, je te passe la main ;)

HTH

**Comment by vdct** [comment]
Super, merci @deuzeffe :)
Je case ça dans la semaine, le temps de comprendre si c'est goût banane ou framboise cette fois-ci /o\

**Comment by vdct** [comment]
C'est en prod, merci @deuzeffe :+1:
