### ISSUE TITLE
"name":"None" dans export JSON

### ISSUE THREAD

**Issue by cquest** [osm-fr/bano#209]
Exemple:

{"id":"010010075Z","citycode":"01001","type":"street","name":"None","postcode":"01400","lat":"46.151552","lon":"4.956100","city":"L'Abergement-Clémenciat","departement":"Ain","region":"Auvergne-Rhône-Alpes","importance":0.1915,"housenumbers":{"1080":{"lat":46.148658,"lon":4.953113},"374":{"lat":46.153335,"lon":4.95789},"486":{"lat":46.152662,"lon":4.957296},"756":{"lat":46.150705,"lon":4.955215}}}

**Comment by vdct** [comment]
Oh c'est moche ! Merci du signalement

**Comment by vdct** [comment]
Stat du 19/11 :
gzip -cd full.sjson.gz |grep '"None"'|wc -l
0
