### ISSUE TITLE
pertes des GRANT sur les tables rechargées quotidiennement

### ISSUE THREAD

**Issue by cquest** [osm-fr/bano#211]
Dans https://github.com/osm-fr/bano/blob/packaging/copy_table_from_osm_to_cadastre.sh

les tables sont rechargées par un DROP TABLE / CREATE TABLE, les GRANT sont donc perdus et le rendu ne fonctionne plus...

Au moins 2 solution possibles :
- faire le pg_dump avec l'option "-a" pour ne pas inclure la création du schéma + remplacer le DROP TABLE par un TRUNCATE
- refaire un "GRANT SELECT ON latable TO PUBLIC" après le rechargement de celle-ci

**Comment by vdct** [comment]
Dans le .mml il me semble avoir utilisé le rôle CADASTRE justement pour éviter ça. Quel rôle utilises tu ?

**Comment by vdct** [comment]
En inspectant les tables à l'instant toutes sont en GRANT SELECT to PUBLIC donc je ne vois rien à changer, ça semble inclus dans le dump je suppose.

**Comment by cquest** [comment]
Par sécurité, j'ai créé un role "renderd" en select seul (read-only), comme tu le suggérais.
Effectivement, le pg_dump contient un GRANT SELECT ON TABLE public.polygones_insee_geo TO PUBLIC;
Il n'y a pas eu de problème suite aux traitements de cette nuit, je ferme.
