### ISSUE TITLE
Commune manquante ?

### ISSUE THREAD

**Issue by cquest** [osm-fr/bano#215]
Code INSEE 94068 tout vide :(

**Comment by vdct** [comment]
Où ça ?
Je vois plein de monde ici : 
http://bano.openstreetmap.fr/fantoir/#insee=94068&tab=1

**Comment by cquest** [comment]
"Données OSM en date du" est vide, et sur le rendu, pas une adresse verte (alors que tout ou presque doit y être): http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#15/48.7981/2.4950

```
select source, count(*) from cumul_adresses where insee_com = '94068' group by 1;
  source  | count 
----------+-------
 BAN      | 16971
 CADASTRE | 14544
(2 rows)

```

**Comment by vdct** [comment]
Le souci venait du stockage des CPs dans les tables cumul_* : stockage sur 5 caractères pas un de plus, ça faisait planter le process de rapprochement à cause des adresses de La Varenne avec double CP. A l'instant 16060 adresses de source OSM pour Saint-Maur, la carte devrait reverdir ;)

**Comment by cquest** [comment]
Yes, bien plus verte !

Plus de nom de commune... peut être parce que, tout est rapproché ? ça doit être ça :)
