### ISSUE TITLE
voie actuelle non rapprochée car voie annulée rapprochée

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/bano#216]
commune Bucey-lès-Gy 70104
un exemple parmi d'autre : Rue de l'europe

dans osm la rue et ses adresses
https://overpass-turbo.eu/s/10HL

dans l'outil du cadastre pdf il y en a 27 adresses
http://cadastre.openstreetmap.fr/data/070/RB104-BUCEY-LES-GY-adresses-addrstreet_mix_en_facade_ou_isole.zip

dans le rendu bano on voit bien toutes les addr,
y compris celle encore absente dans osm

mais dans le comparateur
https://bano.openstreetmap.fr/fantoir/#insee=70104&tab=2
- elle est non rapprochée. quelqu'un comprend pq ?
bien sur on peux forcer en ajoutant la ref
mais même sans ref, le nom exactement identique fait
le rapprochement non ?
- elle est sans adresse, la BAN n'a pas récupéré
les addr du cadastre ?

je te laisse éditer le titre si j'ai mal compris ta réponse :)
dis moi s'il faut un 2ieme ticket pour l'absence d'addr ou si c'est une conséquence de ce bug

**Comment by vdct** [comment]
Le souci est propre à cette voie car dans les [données OSM](https://www.openstreetmap.org/way/164635695/history) on a un rapprochement avec un code FANTOIR obsolète, qui empêche de rapprocher sur le code actuel de la voie. Par suite elle ressort comme à rapprocher. La correction se fait dans les données, en supprimant le Fantoir obsolète

**Comment by Marc-marc-marc** [comment]
ref erronée effacée, on verra ce que cela donne demain.
ne faudrait-il pas éviter un rapprochement avec une ref obsolète ?
ne faudrait-il pas que l'existence d'une ref périnée dans osm apparaissent quelque part ?
une section dans https://bano.openstreetmap.fr/fantoir/#insee=70104&tab=6 ?

**Comment by vdct** [comment]
> ne faudrait-il pas éviter un rapprochement avec une ref obsolète ?

Si, et c'est déjà le cas quand on récupère les codes FANTOIR à la source au moment de procéder aux rapprochements. Mais il y a aussi le principe de respecter les FANTOIRs issus d'OSM, comme c'est le cas pour ton problème ici 

> ne faudrait-il pas que l'existence d'une ref périnée dans osm apparaissent quelque part ?

D'accord avec ça => https://github.com/osm-fr/osm-vs-fantoir/issues/116

**Comment by Marc-marc-marc** [comment]
après suppression de la ref erronée d'un 2ieme way, le rapprochement s'est bien fait dans l'onglet "rapproché avec adresse"
