### ISSUE TITLE
Voie non rapprochée

### ISSUE THREAD

**Issue by gendy54** [osm-fr/bano#217]
http://osmose.openstreetmap.fr/fr/map/#item=7170&class=32&level=1%2C2%2C3&zoom=18&lat=48.641388&lon=2.228878&tags=&fixable=

Rapprochée dans le tableau mais pas sur le rendu Bano. 
ref:FR:FANTOIR=913630483A dans la relation

**Comment by vdct** [comment]
Merci @gendy54 ça devrait être corrigé maintenant
