### ISSUE TITLE
Tests de non-régression suite à la livraison des données depuis une semaine

### ISSUE THREAD

**Issue by alain-andre** [osm-fr/bano#220]
Bonjour, nous utilisons la BANO depuis un certain temps et sommes très content des livraisons de nouvelles données. Nous avons des tests qui nous permettent de garantir la non régression pour nos clients et j'ai quelques questions. 

Nous avons décelé que certaines adresses ont disparues
 
Quand nous avions 
```bash
> 13000 marseille
13000 Marseille (mO | 0.9909090909090909)
```
nous avons
```bash
> 13000 marseille
Allée de Marseille 91300 Massy (31yYDR | 0.715238961038961)
```

Quand nous avions 
```bash
> 20 Route du Rove 13016 Marseille
20 Route du Rove 13016 Marseille (voZPr | 0.9307909090909091)
```

nous avons 
```bash
> 20 Route du Rove 13016 Marseille
20 Route Roy Boissy 60690 Marseille-en-Beauvaisis (18mOG | 0.48638868873062424)
```

Avant 
```bash
> 148 Avenue du Professeur Jean Louis Viala 34090 Montpellier
148 Avenue du Professeur Jean Louis Viala 34090 Montpellier (P65k1 | 0.9398999999999998)
```

Maintenant
```bash
> 148 Avenue du Professeur Jean Louis Viala 34090 Montpellier
Avenue du Professeur Louis Ravas 34000 Montpellier (w53jm | 0.6231371340523884)
```

Pour certaines adresses je pense que c'est lié aux anciennes communes : 

Quand nous avions
```bash
> 5 Place de l'Église 56460 le roc st andre
5 Place de l'Église (Le Roc-Saint-André, Val-d'Oust) 56460 Val d'Oust (GAM9r | 0.7412015117919774)
```

nous avons
```bash
> 5 Place de l'Église 56460 le roc st andre
Roques (poX8y | 0.3462)
```

Certaines adresses n'ont plus aucune correspondance : 

Quand nous avions
```bash
> La Croix Verte 18600 Sagonne
La Croix Verte 18600 Sagonne (2xMwP | 0.9092999999999999)
```

nous avons
```bash
> La Croix Verte 18600 Sagonne
247.5 ms — 1 run(s) — 0 results
```

Pour certaines ce sont des lieux-dits (l'exemple), mais d'autres comme *8 Rue des Musardises 13015 Marseille* sont des adresses.

Pouvez-vous voir ce qu'il en est car si les données sont enrichies des adresses de datagouv, il y a un soucis en ce qui concerne les lieux dits ainsi que les anciennes communes. Aussi je n'explique pas ces adresses qui ont disparues, avez-vous des éléments de réponse ?

**Comment by cquest** [comment]
Sur quelle API et/ou version/config d'addok faites vous ces requêtes ?

Le problème peut en effet provenir des données elles-même ou du moteur de géocodage.

**Comment by cquest** [comment]
**13000 Marseille**
- Marseille ne semble pas figurer dans la liste des communes, tout comme Paris et sûrement Lyon... problème ne non prise en compte des arrondissements municipaux lors de l'export json ?
- le code postal fictif (car inexistant) 13000 est à ajouter, tout comme 69000 et 75000 pour Lyon et Paris

Ceci expliquerai aussi l'absence de la **Route du Rove** (à Marseille) dans les données et donc c'est celle d'Ensuès qui est retournée par addok vue que c'est la seule dans toute la base.

**148 Avenue du Professeur Jean Louis Viala 34090 Montpellier**
Elle ne figure pas dans l'export json

**5 Place de l'Église 56460 le roc st andre**
Absente aussi du json

**La Croix Verte 18600 Sagonne**
Bien présente dans les données, ici c'est addok qui ne la retrouve pas avec une recherche très longue.

Pouvez-vous fournir un EXPLAIN La Croix Verte 18600 Sagonne
et ouvrir une issue sur https://github.com/addok/addok/issues

**Comment by vdct** [comment]
Merci @alain-andre pour vos retours.

> **13000 Marseille**
> 
>     * Marseille ne semble pas figurer dans la liste des communes, tout comme Paris et sûrement Lyon... problème ne non prise en compte des arrondissements municipaux lors de l'export json ?
> 
>     * le code postal fictif (car inexistant) 13000 est à ajouter, tout comme 69000 et 75000 pour Lyon et Paris
> Ceci expliquerai aussi l'absence de la **Route du Rove** (à Marseille) dans les données et donc c'est celle d'Ensuès qui est retournée par addok vue que c'est la seule dans toute la base.

J'ai opéré un 1er niveau de correction sur les arrondissements municipaux de Marseille, dont le schema de données n'était pas homogène avec celui de Lyon et Paris (https://www.openstreetmap.org/changeset/95773666) On verra demain quelles conséquences cela a sur la recherche de voies.
 
> **148 Avenue du Professeur Jean Louis Viala 34090 Montpellier**
> Elle ne figure pas dans l'export json
Problème de rapprochement depuis la bascule Cadastre -> BAN, corrigé ce soir par https://github.com/osm-fr/bano/commit/b3d4e596987c0298d79328c7a328de75d6e5221a

> **5 Place de l'Église 56460 le roc st andre**
> Absente aussi du json
Le rapprochement ne se fait plus depuis la bascule Cadastre -> BAN il y a quelques semaines. L'identification de cette voie dans Fantoir ne se produisait que grâce au Cadastre, qui donnait comme nom "Place de l'Eglise du Roc St André" pour la distinguer de la "Place de l'Eglise de la Chapelle" dans la même commune. Les deux places s'appellent maintenant "Place de l'Eglise" dans la BAN, elles se distinguent par le nom de leur commune d'origine avant fusion. Ce nom n'est pas pris en compte par les processus BANO pour l'instant

**Comment by alain-andre** [comment]
Bonjour @cquest en ce qui concerne la configuration d'addok, la voici : 

```
addok.shell==1.1.0rc1, addok.http.base==1.1.0rc1, addok.batch==1.1.0rc1, addok.pairs==1.1.0rc1, addok.fuzzy==1.1.0rc1, addok.autocomplete==1.1.0rc1, usage_name_LU==1.0.0, usage_name_BAN_FR==1.0.0, search2steps==1.0.0, score_preprocessed_query==1.0.0, luxemburg==1.1.0, luxemburg_clean==1.0.0, france==1.1.0, france_clean==1.0.0, fr==1.0.1, csv==1.0.1
```

En ce qui concerne **La Croix Verte 18600 Sagonne**, je ne la trouve pas dans le json : 

```
18130B131A-1,1,La Croix Verte,18170,Loye-sur-Arnon,CAD,46.627137,2.407227
18130B131A-152,152,La Croix Verte,18170,Loye-sur-Arnon,CAD,46.62607,2.408428
18130B131A-2,2,La Croix Verte,18170,Loye-sur-Arnon,CAD,46.626407,2.408516
18130B131A-206,206,La Croix Verte,18170,Loye-sur-Arnon,CAD,46.62588,2.409103
18130B131A-3,3,La Croix Verte,18170,Loye-sur-Arnon,CAD,46.626296,2.408571
18130B131A-4,4,La Croix Verte,18170,Loye-sur-Arnon,CAD,46.625938,2.4089
18163B105D-108,108,La Croix Verte,18250,Neuvy-Deux-Clochers,CAD,47.277746,2.70428
```

Je n'ai pas créé le ticket côté addok pour le moment, voici le explain : 

```
EXPLAIN La Croix Verte 18600 Sagonne
[394.5] Taken tokens: [<Token sagon>, <Token vert>, <Token 18600>]
[394.5] Common tokens: [<Token kroix>, <Token la>]
[394.5] Housenumbers token: []
[394.5] Not found tokens: []
[394.7] Filters: []
[395.1] ** ONLY_COMMONS_BUT_GEOHASH_TRY_AUTOCOMPLETE_COLLECTOR **
[397.9] ** NO_TOKENS_BUT_HOUSENUMBERS_AND_GEOHASH **
[397.9] ** NO_AVAILABLE_TOKENS_ABORT **
[397.9] ** ONLY_COMMONS **
[398.2] ** NO_MEANINGFUL_BUT_COMMON_TRY_AUTOCOMPLETE_COLLECTOR **
[398.4] ** ONLY_COMMONS_TRY_AUTOCOMPLETE_COLLECTOR **
[398.4] ** BUCKET_WITH_MEANINGFUL **
[398.5] New bucket with keys ['w|sagon', 'w|vert', 'w|18600'] and limit 20
[470.3] 1 ids in bucket so far
[470.4] ** REDUCE_WITH_OTHER_COMMONS **
[470.5] ** ENSURE_GEOHASH_RESULTS_ARE_INCLUDED_IF_CENTER_IS_GIVEN **
[470.7] ** FUZZY_COLLECTOR **
[471.3] Checking cream.
[471.6] Computing results
[471.8] Done getting results data
[482.9] Done computing results
[483.0] Checking cream.
[483.0] Computing results
[483.0] Done computing results
[483.4] Fuzzy on. Trying with [<Token sagon>, <Token vert>, <Token 18600>].
[484.1] Going fuzzy with sagon and ['w|vert', 'w|18600', 'w|kroix', 'w|la']
[509.8] Going fuzzy with vert and ['w|sagon', 'w|18600', 'w|kroix', 'w|la']
[515.0] Checking cream.
[515.1] Computing results
[515.1] Done computing results
[515.3] Fuzzy on. Trying with [<Token sagon>, <Token 18600>, <Token vert>].
[515.3] Going fuzzy with sagon and ['w|vert', 'w|18600']
[518.0] Going fuzzy with vert and ['w|sagon', 'w|18600']
[520.2] ** AUTOCOMPLETE_MEANINGFUL_COLLECTOR **
[520.2] Autocompleting sagon
[521.3] Found tokens to autocomplete set()
[521.3] ** EXTEND_RESULTS_EXTRAPOLING_RELATIONS **
[542.9] Adding to bucket with keys ['w|sagon', 'w|vert', 'w|18600']
[543.7] 1 ids in bucket so far
[543.7] No relation extrapolated.
[543.7] ** EXTEND_RESULTS_REDUCING_TOKENS **
[543.7] Checking cream.
[543.7] Computing results
[543.7] Done computing results
[543.7] Computing results
[543.8] Done computing results
538.6 ms — 1 run(s) — 0 results
```

**Comment by alain-andre** [comment]
@vdct Merci pour les explications et correctifs, je vais tester ça.

**Comment by alain-andre** [comment]
@vdct J'ai une question à propos des lieux-dits. La BANO ne les avait pas auparavant mais aujourd'hui vu qu'elle s'enrichit des données datagouv qui le contient, les a-t-on dans cette nouvelle BANO ?

**Comment by cquest** [comment]
BANO contient les lieux-dits depuis longtemps (type: locality), par contre les adresses numérotées dans les lieux-dits ne sont peut être pas encore dans les exports.

**Comment by alain-andre** [comment]
Merci pour le retour @cquest. En fait j'essaye de trouver un lien entre les adresses qui ne nous retournent plus de résultat mais qui pourtant existent bien sur Google ou Here : 

lat, lng Attendues | lat,lng Google | lat,lng Here | Requête
-- | -- | -- | --
48.5011, 0.1181 | 48.5013,0.1197 | 48.4566, 0.1017 | Maison Neuve 61250 Écouves
47.8047, 5.4986 | 47.8049, 5.4987 | 47.8048, 5.4986 | RUE DE L EGLISE CORGIRNON 52500 CHAMPSEVRAINE
46.8533, 2.8395 | 46.8548, 2.8395 | 46.8534, 2.8399 | La Croix Verte 18600 Sagonne
48.5463, 6.5402 | Retourne la ville | Retourne la ville | Pre Gohi 54300 Moncel-lès-Lunéville
45.3267, -0.1442 | 45.3284, -0.1435 | 45.3269, -0.1442 | Rossignoux 16480 Boisbreteau
49.7538, 3.0675 | 49.7574, 3.0712 | 49.7610, 3.0773 | Route de Saint-Quentin 80400 Ham

**Comment by alain-andre** [comment]
@vdct super pour Marseille, les nouvelles données contiennent bien les adresses. Merci

**Comment by vdct** [comment]
Bonsoir, voici quelques éléments d'analyse

> Merci pour le retour @cquest. En fait j'essaye de trouver un lien entre les adresses qui ne nous retournent plus de résultat mais qui pourtant existent bien sur Google ou Here :
> lat, lng Attendues 	lat,lng Google 	lat,lng Here 	Requête
> 48.5011, 0.1181 	48.5013,0.1197 	48.4566, 0.1017 	Maison Neuve 61250 Écouves

Pas de "Maison Neuve" dans OSM, ni dans la BAN qui connaît un "Lieu Dit les Maisons Neuves". Seul le Cadastre connait un "Maison Neuve", donc votre échec de recherche est dû à notre changement de fournisseur (Cadastre => BAN)

> 47.8047, 5.4986 	47.8049, 5.4987 	47.8048, 5.4986 	RUE DE L EGLISE CORGIRNON 52500 CHAMPSEVRAINE

Le nom connu de la BAN et de BANO est juste "Rue de l'Eglise" sans ajout de "Corgirnon"

> 48.5463, 6.5402 	Retourne la ville 	Retourne la ville 	Pre Gohi 54300 Moncel-lès-Lunéville

Pré Gohi est bien dans le JSON

> 45.3267, -0.1442 	45.3284, -0.1435 	45.3269, -0.1442 	Rossignoux 16480 Boisbreteau

On a dans le JSON Rossignoux-ouest et Rossignoux-est, pas strictement Rossignoux

> 49.7538, 3.0675 	49.7574, 3.0712 	49.7610, 3.0773 	Route de Saint-Quentin 80400 Ham

OSM connaît cette voie mais on ne l'exporte pas faute de numéros. La BAN connaît par ailleurs une 'Rue de Saint-Quentin' avec des numéros, mais pas la 'Route de Saint-Quentin'.
