### ISSUE TITLE
Problème avec le département 43 Haute-Loire

### ISSUE THREAD

**Issue by Olyon** [osm-fr/bano#221]
Il n'y a rien dans https://bano.openstreetmap.fr/fantoir/voies_recentes_manquantes.html#dept=43
Il semble n'y avoir aucune adresses dans 43.

**Comment by vdct** [comment]
Merci @Olyon c'est réparé. L'origine : le contenu en adresses BAN était vide pour juste ce département suite à la dernière mise à jour. Je ne me l'explique pas, faudra surveiller...

**Comment by Olyon** [comment]
Merci
