### ISSUE TITLE
Fantoir d'hiver pas (encore) confiné

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/bano#227]
Maître @vdct,

Le FANTOIR nouveau est sorti, ici : https://data.economie.gouv.fr/api/datasets/1.0/fichier-fantoir-des-voies-et-lieux-dits/attachments/fichier_national_fantoir_situation_janvier_2021_zip/

Signé La Gardienne.

**Comment by vdct** [comment]
merci @deuzeffe 
j'espère que tu apprécieras mon commentaire de commit :p

**Comment by deuzeffe** [comment]
@vdct hihi (vivi ou emacsemacs)
