### ISSUE TITLE
Voie non rapprochée

### ISSUE THREAD

**Issue by adrienandrem** [osm-fr/bano#234]
Bonjour,

le [chemin 879371363](https://osm.org/way/879371363) n'est pas rapproché avec la [voie FANTOIR 973050784S](https://bano.openstreetmap.fr/fantoir/index.html#insee=97305&tab=0) ([rendu](https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#19/4.91778/-52.38333))  
mais _Libellé BAN_ est bien "Chemin des Papillons".

Je ne comprends pas ce qui empêche le rapprochement :thinking:

**Comment by vdct** [comment]
Bonjour Adrien,
je constate par ton message qu'il manque des données dans la BD OSM qui sert pour alimenter BANO. La rue que tu indiques date du 23/02, date d'une coupure de la BD pour maintenance. Dans le doute je procèderai ce WE à un rechargement de la base, tout devrait rentrer dans l'ordre.
Merci pour le signalement

**Comment by vdct** [comment]
Après rechargement de la BD ce matin la voie est bien présente, et donc le rapprochement se fait.
