### ISSUE TITLE
Données BAL pas intégrées pour Lambersart ?

### ISSUE THREAD

**Issue by arnaud-jacquemin** [osm-fr/bano#236]
Bonjour,

Je viens de découvrir le site https://adresse.data.gouv.fr/, et en regardant Lambersart, j'y vois des adresses qui n'étaient pas connues de l'outil "OSM vs. FANTOIR" ni de la couche BANO. Si je comprends bien, d'après le site Base Adresse Nationale, les adresses en questions seraient issues de la "base adresse locale (commune)". 

Cela concerne l'Avenue de la Marne à Lambersart, pour laquelle toutes les adresses sont sur https://adresse.data.gouv.fr/base-adresse-nationale/59328_vzwi91#18.32/50.6437/3.028  
‎Or sur BANO il n'y a que mes saisies (suite relevé sur terrain) : https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#18/50.643145/3.02825  
C'est à dire : je vois mes points verts, mais pas de points bleus ou orange. Et sur "OSM vs. FANTOIR", je crois me souvenir que la voie était dans l'onglet "voies sans adresses" avant que je ne fasse le relevé  .

Une cause possible : j'ai saisi "Rue de la Marne", mais la voie s'appelle "Avenue de la Marne" sur la adresse.data... Cependant je ne vois pas d'Avenue de la Marne sur OSM vs. FANTOIR (code commune 59328)

Il y a peut-être un cas similaire avec la rue Saint Saens, pour laquelle je vois 10 numéros sur la BAL : https://adresse.data.gouv.fr/base-adresse-nationale/59328_1270#16.7/50.6575/3.0368
Mais uniquement des points verts sur la carte BANO : https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#20/50.65745/3.03646
Encore une fois le libellé n'est pas identique dans les deux bases : "Rue Camille Saint Saens" dans la BAL vs. "Rue Saint-Saëns" dans OSM.

Il s'agit peut-être d'une fausse alerte, mais cela me donne l'impression que les données BAL de Lambersart ne sont pas prises en compte dans BANO.

Merci d'avance !

**Comment by Olyon** [comment]
Bonjour,

Je pense que le probleme vient du fait que l'Avenue de la Marne comme la Rue Camille Saint Saens n'a pas de code Fantoir donc n'apparait pas dans OSM vs Fantoir et le choix a été fait de n'afficher sur la couche BANO que les numéros et voies avec code Fantoir.

 C'est bien l'Avenue de la Marne d'après une photo sur Mapillary : https://www.mapillary.com/app/?lat=50.644401&lng=3.027452999972222&z=17&focus=photo&pKey=0rwLNSzArucBf175e4_MlA&x=0.5180303397650257&y=0.418724298625879&zoom=0
Pour Camille Saint Saens, il semble y avoir le prénom https://www.mapillary.com/app/?lat=50.65767699997222&lng=3.037371999972222&z=17&pKey=-LuYwotYwDsOk6sjlZlXFA&focus=photo&x=0.5839375352860062&y=0.4232084511904496&zoom=0

J'ai modifié sur OSM en laissant les code Fantoir. Je ne sais pas si BANO va faire le lien avec les adresses de la BAL et si du bleu va apparaitre sur le rendu BANO. On le sera 

Soit le changement de nom est récent et la commune n'a pas encore transmis les modifications dans le Fantoir ou alors elle n'a jamais pris la peine de corriger l'erreur pour ces rues même si elle a ajouté de nouvelles rues en 2016 et 2019.

**Comment by vdct** [comment]
Les 2 rues ont depuis obtenu un code Fantoir, et elles apparaissent dans l'onglet des voies intégrées avec adresses.
