### ISSUE TITLE
Plus de mise à jour ?

### ISSUE THREAD

**Issue by Olyon** [osm-fr/bano#239]
Il me semble que les mises à jour ne se font plus. Ni les journalières, ni celle forcés que l'on peux faire sur les pages des communes. 
Exemple : https://bano.openstreetmap.fr/fantoir/index.html#insee=07315&tab=0
Plusieurs noms de rue ont été ajouté dans osm sur la commune le 30/03 mais le rapprochement ne s'est pas fait (il est indiqué : Données OSM en date du | 05-03-2021 00:21:20) et la rue est trouvée lorsque l'on clic sur "relation".

**Comment by deuzeffe** [comment]
Idem sur 87001 : affiché "dernière mise à jour et rapprochement : 28-03-2021." 

Réel pb de màj ou simple pb d'affichage ou autre ?

**Comment by gitouche-sur-osm** [comment]
Constaté aussi mais pas eu le temps de signaler. "Dernier rapprochement BAN le 28-03-2021 02:34:37" pour 40046 qui ne devrait plus avoir 33 voies FANTOIR sans rapprochement OSM mais bien moins.

Merci

**Comment by vdct** [comment]
Merci pour vos signalements @Olyon @deuzeffe  & @gitouche-sur-osm et désolé pour le délai de réponse. J'ai cassé le process de mise àjour avec le commit https://github.com/osm-fr/bano/commit/e8a44b5cc3d2aa925884c55b914afef80eb81384 il y a une semaine en effet. Ca devrait rentrer dans l'ordre à partir de cette nuit suite à https://github.com/osm-fr/bano/commit/353067377208d71c63bf1af97b6f8cb2d07fca77

**Comment by deuzeffe** [comment]
@vdct merci à toi pour la réponse et la réactivité (sissi, quand même :P)

**Comment by deuzeffe** [comment]
@vdct ce matin (> 06:00 mais < 07:00) : 
- date du dernier rapprochement : celle du jour -> OK
- date des données OSM: toujours coincée au 28-03 -> rechargement à la main -> date OK

HTH

**Comment by vdct** [comment]
@deuzeffe  Aaaarg mais oui ça va aider, merci !

**Comment by vdct** [comment]
@deuzeffe je repense à un point : est-ce que la commune sur laquelle tu regardes le souci a eu à ta connaissance des modifs dans OSM sur la journée d'hier ? La màj nocturne ne cible que les communes modifiées dans les dernières 24h

**Comment by deuzeffe** [comment]
@vdct non, pas de modif. depuis "un certain temps" : ça essplique donc ! Merci pour ta patience ;)
