### ISSUE TITLE
Rapprochement avec leisure=park ?

### ISSUE THREAD

**Issue by nuxper** [osm-fr/bano#240]
J'ai un rapprochement manquant à Lyon 2, Place Camille Georges, ( 693821180X sur http://bano.openstreetmap.fr/fantoir/#insee=69382&tab=0 ) qui est, si j'ai bien compris, dû au fait que la place est décrite comme un leisure=park .

La place étant vraiment piétone, avec un peu de verdure et pas ou peu de passage de véhicule, le tagging me semble plutôt bon.
Le codage des adresses le long de la place a été réalisé avec le schéma addr:street plutôt qu'une relation associatedStreet.

Ai-je bien compris le problème ?
Si oui, est-il possible de faire le rapprochement fantoir - leisure=park ?

Je veux bien aider si besoin si quelqu'un veut bien me guider vers le bon endroit.

**Comment by vdct** [comment]
Bonjour,
par défaut en effet pas de rapprochement sur les polygones avec leisure=park, car ils sont trop peu nombreux dans FANTOIR, ça occasionnerait pas mal de "bruit" dans les rapprochements. Cependant le fait d'ajouter le code FANTOIR sur l'objet quel qu'il soit permet de forcer le rapprochement. C'est l'objet de [la fin de cette ligne](https://github.com/osm-fr/bano/blob/packaging/bano/sql/highway_suffixe_insee.sql#L46). Donc il devrait suffire d'ajouter ce tag pour que le rapprochement s'effectue

**Comment by nuxper** [comment]
Ha ok parfait ! ;)
Je vais faire comme ça, je clos donc le ticket.
Est-ce que tu veux que je documente le cas sur https://wiki.openstreetmap.org/wiki/Contribuer_%C3%A0_la_BANO ?
Merci en tout cas !

**Comment by vdct** [comment]
> Est-ce que tu veux que je documente le cas sur https://wiki.openstreetmap.org/wiki/Contribuer_%C3%A0_la_BANO ?

Si tu n'en vois pas déjà de mention, alors volontiers oui. Merci :)
