### ISSUE TITLE
FANTOIR de printemps

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/bano#242]
Toc toc, c'est la gardienne, qui annonce au mainteneur en chef que le FANTOIR nouveau est arrivé, ici : https://data.economie.gouv.fr/api/datasets/1.0/fichier-fantoir-des-voies-et-lieux-dits/attachments/fichier_national_fantoir_situation_avril_2021_zip/

Bons tripatouillages !

HTH

**Comment by vdct** [comment]
Merci m'dame @deuzeffe :)
C'est mis à jour

**Comment by deuzeffe** [comment]
Mici M'sieur. Je me demandais si, pour dans 3 mois, je pouvais pas éditer moi-même le fichier (dans la bonne branche) : vue la complexité de la tâche, je devrais pouvoir y arriver. Et faire une PR que tu n'aies plus qu'à merger si tu trouve ça correct (si non, tu m'en**eules, pas de souci :p) Quoi t'en penses ?

**Comment by vdct** [comment]
YES !
En voilà une bonne idée 👍

**Comment by deuzeffe** [comment]
Merci pour ton enthousiasme ;)

Si j'ai tout compris : 
- dans  https://github.com/osm-fr/bano/blob/packaging/load_fantoir.sh changer le nom du fichier à télécharger à la ligne kivabien (L8 actuellement) ;
- dans https://github.com/osm-fr/osm-vs-fantoir/blob/bano_v2/includes/footer.html changer le mois/la date de la source à la ligne kivabien (L17 actuellement)

C'est ça ?

(Rq : je fais tout par le web, je ne sais pas si ça a une importance/influence).

**Comment by vdct** [comment]
Oui c'est pile ça.
Pour l'aspect web je n'ai pas idée, j'espère que ça ne change rien
