### ISSUE TITLE
[bano-69] 9,8k numbers=99999

### ISSUE THREAD

**Issue by SGrenet** [osm-fr/bano#244]
Bonjour,

Dans le Bano-69 je compte 9,8k occurrences du No 99999 sur les 360k lignes du fichier
Exemple : 
690030015D-99999,99999,Rue Armand Zipfel,69250,Albigny-sur-Saône,OD,45.857088,4.833391
690030020J-9,9,Avenue des Avoraux,69250,Albigny-sur-Saône,OSM,45.873626,4.829983
690030020J-99999,99999,Avenue des Avoraux,69250,Albigny-sur-Saône,OD,45.871577,4.82959

Souvent des rues sans No de seuil ou en fin de numérotation

Est-ce normal?
J'ai regardé un autre département et aucune occurrence de ce "No 99999" qui semble représenter un seuil sans numérotation.

Sylvain

**Comment by vdct** [comment]
Bonjour Sylvain,
je ne connais pas la signification du 99999, rien n'est évoqué dans le [guide des bonnes pratiques](https://adresse.data.gouv.fr/data/docs/guide-bonnes-pratiques-v1.0.pdf) d'Etalab. La source de ces numéros semble être le flux des BAL (Bases Adresse Locales). Le Rhône n'est pas le pire: je compte 17k occurrences dans le dept 22, 14.5k pour le 69. Ca fait beaucoup dans les 2 cas ceci dit.

**Comment by SGrenet** [comment]
Bonjour,
Merci pour cette réponse. 
Je n'avais pas tout les éléments, en particulier le workflow ou la source de ces datas.
Comment pouvons nous procéder pour que ce soit amélioré en amont ou en connaitre la raison pour le traiter en aval?
Surtout qui s'en charge ;) 

Sylvain

**Comment by vdct** [comment]
Si on les considère farfelus, ça aurait du sens de ne pas alimenter BANO avec. Et dans ce cas l'endroit où agir est en début de chaîne. On peut assez simplement détecter la valeur 99999 (et peut-être quelques autres) afin de les filtrer. Cependant vu que la source est côté BAL ça questionne sur l'intérêt de garder ces BALs dans BANO. J'avais il y a quelques mois an analysé leur apport pour savoir si l'arrivée de la source BAN permettait de les supprimer, et ça n'était pas évident. Ca vaudrait le coup de refaire l'analyse en expurgeant ces n° factices, pour (re)mesurer l'apport des BAL. Possible que la décision ne soit plus la même aujourd'hui en conséquence.

**Comment by Olyon** [comment]
Sur https://adresse.data.gouv.fr/bases-locales pour la "spécification d’un format d’échange, aujourd’hui en version 1.2.", il nous renvoi vers https://aitf-sig-topo.github.io/voies-adresses/files/AITF_SIG_Topo_Format_Base_Adresse_Locale_v1.2.pdf
Et là on a  : 
"Cas des voies et lieux-dits sans adresses
Le modèle de données proposé ci-après doit pouvoir lister les voies ou les lieux-dits sans adresse. C’est, par exemple, le cas des ronds-points ou de carrefours dénommés qui sont rarement l’objet d’une numérotation ainsi que les lieux-dits pour lesquels la numérotation des bâtiments n’a pas encore été effectuée.
Une convention a été retenue: mettre «99999» comme numéro d’adresse signifiant que l’enregistrement traité est une voie sans adresse.
Si le fournisseur / producteur du jeu de données est en capacité de le faire, il fournira des coordonnées permettant de localiser la voie sans adresse sur le territoire (ex: centroïde d’un rond-point, pseudo centre de gravité d’un lieu-dit). "

Donc c'est pour faire apparaitre dans la BAL les voies sans adresse et comme la présence du numéro est obligatoire, ils ont choisi ce 99999.

Par contre j'ai regarder la BAL de la Métropole de Lyon, il y a des voies sans adresses mais toutes les voies avec adresses ont aussi une ligne avec comme numéro 99999.

**Comment by vdct** [comment]
Merci @Olyon pour l'explication. On a déjà dans BANO le principe de fournir un point par voie pour permettre le géocodage à la rue quand aucun n° n'est fourni. La géométrie de ce point est déduite de la géométrie de la voie OSM correspondante.
Pour les lieux-dits c'est le même principe, mais en partant des nodes place=* d'OSM. Donc supprimer en amont les n° "99999" devrait dégrader le contenu exporté à la marge, là où on manque de contenu OSM "voie" ou "lieu-dit". C'est au moins une solution court-terme tant qu'une vraie prise en compte de ces peudo-adresses des BALs n'est pas codée.

**Comment by vdct** [comment]
La gestion au cas par cas des numéros non pertinents est désormais possible sur les pages https://bano.openstreetmap.fr/fantoir/ (via https://github.com/osm-fr/osm-vs-fantoir/issues/74)
