### ISSUE TITLE
Fantoir estival 2021

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/bano#247]
Il est arrivé \o/ (il y a 3 jours, je laggue /o\ )

Comme je disais (https://github.com/osm-fr/bano/issues/242#issuecomment-834665353) je vais essayer de le mettre à jour moi-même. @vdct  : tu surveilles, hein ? ;)

**Comment by vdct** [comment]
Yes @deuzeffe je suis zaux zaguets 0_0
Go ! Go !

**Comment by deuzeffe** [comment]
Voilà, c'est fait et la PR aussi. @vdct à toi de valider (ou pas :p)

**Comment by vdct** [comment]
Merci, contenu déployé :+1: :1st_place_medal:
