### ISSUE TITLE
Landuse: residential reconnue dans rapprochement

### ISSUE THREAD

**Issue by operon** [osm-fr/bano#249]
Dans Fantoir et donc BAN il existe des "Lotissement", "Cité" qui sont representés par des landuse:resiential dans OSM.
Il semble que le rapprochement ne soit pas éffectué.

**Comment by vdct** [comment]
Désolé pour le délai @operon 
Tu as des exemples ? Le code envisage bien les cas que tu cites : https://github.com/osm-fr/bano/blob/packaging/bano/sql/point_par_rue_complement_insee_nocache.sql#L32

**Comment by operon** [comment]
Je ne trouve plus d'exemple.
Soit c'est corrigé soit je me suis trompé
Merci
