### ISSUE TITLE
Présence des anciennes commues 

### ISSUE THREAD

**Issue by alain-andre** [osm-fr/bano#250]
Lié aux [245](https://github.com/osm-fr/bano/issues/245), [220](https://github.com/osm-fr/bano/issues/220)

Bonjour, nous avons remarqué que certaines anciennes communes sont présentes dans le json comme *saint eutrope* ou *lamerac* et d'autre pas du tout comme *saint laurent de belzagot* ou *juillaguet* y-a-t-il une règle particulière ?

Quelques exemples:

 - Route de Jonzac LAMERAC -> Route de Jonzac 16300 Montmérac 
 - Rue de la cure saint laurent de belzagot -> NOK
 - Rue des tortillons saint eutrope -> Rue des Tortillons 16190 Montmoreau
 - Chez bic CHAVENAT -> NOK

**Comment by vdct** [comment]
Il n'y a pas de règle particulière liée aux anciennes communes. Ce qui fait foi pour BANO est le [COG (Code Officiel Geographique)](https://www.insee.fr/fr/information/2560452) mis à jour chaque année, et qui indique les communes ayant été absorbées au cours d'une fusion.

**Comment by frodrigo** [comment]
La BAN donne des informations sur les communes déléguées, alors que la BANO ne le fait pas. Ce qui limite les résultats lors de la recherche d'adresses.


BANO
```json
{
    "id": "162300382N",
    "citycode": "16230",
    "type": "street",
    "name": "Impasse des Alandiers",
    "postcode": "16190",
    "city": "Montmoreau"
}
```

BAN
```json
{
    "id": "16314_0010",
    "name": "Impasse des Alandiers",
    "postcode": "16190",
    "citycode": [
        "16230",
        "16314"
    ],
    "oldcitycode": "16314",
    "city": [
        "Montmoreau",
        "Saint-Eutrope"
    ],
    "oldcity": "Saint-Eutrope"
}
```

BANO le faisait-il et ça a été supprimé ? https://github.com/osm-fr/bano/issues/224

Est-ce envisageable de supporter les communes déléguées, associées et autres, voir même les fusionnées ?

**Comment by vdct** [comment]
> BANO le faisait-il et ça a été supprimé ? #224

Non car BANO n'a jamais combiné plusieurs communes dans la description d'une adresse. Le rapprochement sur les anciennes communes se faisait au détriment de celui sur les communes fusionnées.


> Est-ce envisageable de supporter les communes déléguées, associées et autres, voir même les fusionnées ?
Oui, en s'appuyant sur leur présence dans OSM avec admin_level=9 et d'autres attributs tels que disused:admin_level et/ou admin_type:FR
