### ISSUE TITLE
Fantoir automnal 2021

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/bano#253]
C'est Noël avant l'heure : le Fantoir situation novembre 2021 est arrivé \o/

@vdct Je mets à jour et tu me surveilles !

Stay tuned!

**Comment by vdct** [comment]
Merci @deuzeffe !
Code mergé, mais pas encore appliqué aux données. Je fermerai le ticket quand ce sera fait (demain normalement)

**Comment by deuzeffe** [comment]
Plaisir d'offrir ;)

**Comment by vdct** [comment]
Voilà, Fantoir appliqué hier à toutes les sources, BANO est à jour. Merci :)

**Comment by deuzeffe** [comment]
Merci à toi pour la confiance !
