### ISSUE TITLE
ref:FR:FANTOIR présent, mais pas de rapprochement

### ISSUE THREAD

**Issue by adrienandrem** [osm-fr/bano#255]
Le rapprochement pour la voie `973020535J` ne s'effectue pas ([page FANTOIR](https://bano.openstreetmap.fr/fantoir/#insee=97302&tab=0), [carte](http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#18/4.935175/-52.331287))  
pourtant [Overpass](https://overpass-turbo.eu), pour `type:way and highway=* and "ref:FR:FANTOIR"="973020535J" in Cayenne`, retourne bien https://osm.org/way/606414683

**Comment by vdct** [comment]
Le rapprochement s'effectue sur un autre code : 973020534H qui est celui de la rue de même nom rive droite. Dans les traitements de rapprochement on considère qu'à un nom dans OSM ne correspond qu'un seul code Fantoir à rechercher. On atteint les limites de cette logique dans le cas présent, et aussi dans le cas de voies homonymes dans une même commune, issues de voies de communes fusionnées.
