### ISSUE TITLE
Plus de mise à jour ?

### ISSUE THREAD

**Issue by Olyon** [osm-fr/bano#258]
J'ai l'impression que les mises à jours ne se font plus depuis une dizaine de jours (depuis que le serveur qui hébergé bano à planté ?)

Par exemple, https://bano.openstreetmap.fr/fantoir/index.html#insee=38519&tab=0
une grande partie des rues a été ajouté dans osm le 17 novembre.

**Comment by vdct** [comment]
Si je me fie aux dates de màj ça semble aller, les données OSM sont de cette nuit. Tu as un exemple ?

**Comment by Olyon** [comment]
Sur la page, il est indiqué que la mise à jour est faite mais par exemple : 
https://www.openstreetmap.org/way/162589659/history
l'"impasse des Alpes" a été ajoutée il y a 12 jours

**Comment by vdct** [comment]
Ah oui en effet. J'essaie de regarder ce soir avec un accès à la BD

**Comment by vdct** [comment]
Diagnostic assez simple : je n'ai pas l'Impasse des Alpes en base, ni l'Impasse du Mont Blanc voisine et qui a le même âge. Ca ressemble à un loupé de mise à jour. Je viens de relancer le chargement complet de la base, à suivre demain.

![Capture d’écran de 2021-11-29 23-40-56](https://user-images.githubusercontent.com/2237260/143954374-693be304-e301-4dad-b3a6-20b362e730b5.png)

**Comment by vdct** [comment]
> Je viens de relancer le chargement complet de la base

@Olyon je te laisse vérifier mais j'ai l'impression que c'est rentré dans l'ordre, dans le cas de Valencin

**Comment by Olyon** [comment]
Impeccable !
Il y avait d'autres communes où j'avais fait des modifications qui n'étaient pas présentes dans BANO et forcer la mise à jour ne changeait rien ...
Là je viens de faire une modification, j'ai forcé la mise à jour et ça c'est mis à jour.
Donc tout marche très bien !
