### ISSUE TITLE
FANTOIR printanier 2022

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/bano#265]
Hello,

Le (presque ?) dernier FANTOIR de ce nom est là : https://data.economie.gouv.fr/api/datasets/1.0/fichier-fantoir-des-voies-et-lieux-dits/attachments/fichier_national_fantoir_situation_avril_2022_zip/

@vdct je mets à jour (et tu surveilles !)

Done.

**Comment by deuzeffe** [comment]
@vdct de rien de rien ;)

Tu as des info. sur la structure du futur nouveau fichier remplaçant Fantoir ? (impossible de retrouver notre discussion à ce propos sur je ne sais quel commit :/)

**Comment by vdct** [comment]
J'avais téléchargé un exemple mais ça date un peu et je ne m'y suis pas repenché faute de temps. Ce FANTOIR printanier 2022 nous laisse un peu de répit bienvenu :)

**Comment by deuzeffe** [comment]
De mémoire, le dernier devrait être l'estival publié en juillet. Faut que je retrouve le lien vers l'article du blog que tu m'avais indiqué.
