### ISSUE TITLE
Disparition de la couche BANO à un certain niveau de zoom

### ISSUE THREAD

**Issue by fnuttens** [osm-fr/bano#274]
Le passage du niveau 15 au niveau 16 fait disparaître la BANO sur https://tile.openstreetmap.fr/~cquest/leaflet/bano.html. J'ai pu observer ce comportement sur Firefox, Chrome et Safari, donc c'est vraisemblablement côté serveur qu'il y a un souci.

Niveau 15 :

<img width="275" alt="15" src="https://user-images.githubusercontent.com/8812165/178016483-d83920b0-9dd6-4c57-975f-47ead9a94956.png">

Niveau 16 :

<img width="528" alt="16" src="https://user-images.githubusercontent.com/8812165/178016565-5a3cae78-4e46-401c-bdf6-5effb940c0cb.png">

**Comment by vdct** [comment]
Je soupçonne un souci de http/https car en https via JOSM j'ai sans souci des tuiles au niveau 19. Sur layers elles sont appelées en http. Ping @cquest

**Comment by fnuttens** [comment]
@vdct avec cURL je reçois des 404 via HTTP également :

```bash
$ curl https://c.layers.openstreetmap.fr/bano/15/17070/11293.png -i
HTTP/1.1 200 OK
...
$ curl https://c.layers.openstreetmap.fr/bano/16/34139/22586.png -i
HTTP/1.1 404 Not Found
...
$ curl http://c.layers.openstreetmap.fr/bano/16/34139/22586.png -i
HTTP/1.1 404 Not Found
...
```

**Comment by fnuttens** [comment]
Il semble que le problème ne concerne qu'un faible partie du territoire, pour le moment je ne l'ai observé que dans quelques communes au Nord-Ouest de Strasbourg.

**Comment by fnuttens** [comment]
@cquest ça fonctionne à nouveau de mon côté, malgré une certaine latence.
