### ISSUE TITLE
Voies dans OSM et Fantoir mais non rapprochées

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/bano#275]
Bonjour,

Pour la commune de Limoges (87085), j'ai trouvé des voies non numérotées non rapprochées (onglet 2) mais connues d'OSM (onglet 6). Par exemple :
- ALL SPINOSA https://www.openstreetmap.org/way/71195960 (service)
- ART ANCIENNE ROUTE DE PARIS https://www.openstreetmap.org/way/447199932 (secondary)
- BD GENEVI DE GAULLE ANTHONIOZ https://www.openstreetmap.org/way/26301717 (primary)

Pas réussi à trouver un point commun à tout ça. Et avant de forcer le rapprochement via le code Fantoir, autant le signaler, au cas où il y aurait matière à modifier le code (?)

À noter que dans la BAL/BAN (https://adresse.data.gouv.fr/base-adresse-nationale/87085), les voies non numérotées de la commune sont déclarées en "Lieu-dit" (aucune idée si c'est ce qui est préconisé par ETALAB/Mes adresses)

À noter aussi que le FANTOIR n'est pas du tout à jour par rapport à la réalité du terrain. Ou la commune ou la DGFiP ou les deux sont... "en retard" ?

HTH

**Comment by vdct** [comment]
J'ai l'impression qu'on peut expliquer chaque cas avec une raison différente

> * ALL SPINOSA https://www.openstreetmap.org/way/71195960 (service)

SpinoSa dans FANTOIR vs SpinoZa dans OSM : ça suffit à empêcher le rapprochement. Le ref:FR:FANTOIR est typiquement requis ici pour faire le lien

> * ART ANCIENNE ROUTE DE PARIS https://www.openstreetmap.org/way/447199932 (secondary)

ART ANCIENNE ROUTE ne fait pas partie des formes connues de 'Ancienne route' qu'on trouve au début de https://github.com/osm-fr/bano/blob/master/bano/dictionnaires/abrev_type_voie.txt => c'est à rajouter dans ce fichier
 
> * BD GENEVI DE GAULLE ANTHONIOZ https://www.openstreetmap.org/way/26301717 (primary)

Le nom diffère à cause du prénom tronqué => ça suffit aussi à empêcher le rapprochement. ref:FR:FANTOIR demandé à la barre itou

**Comment by vdct** [comment]
> Donc, la ligne 4 ANCIENNE ROUTE ANCIENNE ROUTE ART ne suffit pas ?

Non car elle va chercher à remplacer "ANCIENNE ROUTE ANCIENNE ROUTE" par "ART", et donc dans ton exemple rien ne sera remplacé. Il faut ajouter une ligne "ART ANCIENNE ROUTE" => "ART", je fais ça de suite

**Comment by deuzeffe** [comment]
Ça a admirablement bien fonctionné : la voie est rapprochée autoimagiquement (modulo ton commit).

Grand merci à toi !

(je ferme)
