### ISSUE TITLE
Numérotation des lieux-dits

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/bano#277]
Bonjour,

Soit la commune 87001 ("ma mienne").

La commune **n'a pas déclaré** les lieux-dits comme tels mais comme voies. Et elle a établi le plan d'adressage : n° nom du lieu-dit (sans attribuer le nom du lieu-dit aux voies qui y sont).

Toutes les adresses que j'ai intégrées sont dans des associatedStreet avec role=street pour les voies **sauf** pour les lieux-dits.
Les lieux-dits sont tagués place=hamlet+name=lenomkivabien et pas possible de faire une associatedStreet avec un role=place, le validateur JOSM (ou autre) veut pas :-( 
Donc, j'ai intégré les adresses *à l'allemande* : addr:housenumber+addr:place

Sauf que quand je joue avec Pifomètre, évidemment, il ne voit pas que la numérotation est déjà présente dans osm et demande de l’intégrer. Et il me propose soit des points addr:housenumber+addr:street soit une relation avec juste le rôle house pour les numéros.

Je crains que la façon qu'a eu la commune de déclarer les lieux-dits soit la cause de cet imbroglio et je ne vois pas comment guérir Pifomètre de sa cécité. 

Toute idée bienvenue, merci.

**Comment by vdct** [comment]
Un sujet qu'il est vieux (https://github.com/osm-fr/bano/issues/149) et jamais adressé (tu l'as ?). Merci d'y revenir, ça permet de voir qu'on a 13K objets concernés en France (https://taginfo.openstreetmap.fr/keys/addr:place#map), ça devient tout à fait pertinent pour s'arracher les cheveux dessus. J'ai pas d'idée de comment ruser d'ici là avec Pifomètre, le but reste quand même de remplir OSM proprement avant tout.

**Comment by deuzeffe** [comment]
> Un sujet qu'il est vieux (#149)

Mince, j'avais mal réglé mon moteur de recherche pour savoir si ce n'avait pas déjà été traité.

> jamais adressé (tu l'as ?)

Je ne vois **absolument pas** de quoi tu veux parler.

> Merci d'y revenir

Et bientôt, tu risques de devoir dire Mercy!

> J'ai pas d'idée de comment ruser d'ici là avec Pifomètre, le but reste quand même de remplir OSM proprement avant tout.

Si on part du principe que 1/ OSM est correctement rempli : OK puis on enchaîne sur 2/ qualifier le couple lieux-dit/adresse avec le flag kivabien (comme ce qui est fait pour les anomalies ou les non-rapprochements de voies) : est-ce que dans un premier temps ça peut t'éviter des accès de trichotillomanie ? Même si ça fait un peu poussière sous le tapis :(

On peut aussi militer pour que le role=place soit reconnu dans les associatedStreet ou proposer, comme disait @Bibi56, un associatedPlace ou te condamner à torturer ton code jusqu'à la résolution de l'affaire (détecter les couples addr:housenumber/addr:place déjà présents ? Avec un risque de faux positifs non négligeable au vu de ce que raconte taginfo ?) ou à l’apparition d'une calvitie généralisée. mais ça risque d'être plus long (et ça ne sera pas forcément bon).

Bref, fais au mieux.

**Comment by Bibi56** [comment]
@deuzeffe, comme @vdct était aussi pour associatedPlace, _une_ volontaire pour proposer sur [OSM-talk-fr] et ensuite le cas échéant sur la liste internationale ?

**Comment by deuzeffe** [comment]
Je crois que @Bibi56 me trolle... 

@vdct fais au plus simple (?) pour toi et au plus efficace pour osm.

**Comment by Bibi56** [comment]
> On trouve 0 occurrence d'associatedPlace dans le monde

@vdct ça me semble plutôt sain de ne pas procéder par création puis adoption par « de facto ». Après si tu considères qu’une `associatedStreet` peut-être détournée, pourquoi pas (en ajoutant ici un `place=hamlet`). Par contre avec ta logique on va laisser tomber les associatedStreet car pourquoi dépenser de l’énergie alors qu’une modélisation pourrie avec duplication d’informations fait le taf ?

@deuzeffe c’est juste qu’étant la dernière à trouver l’idée bonne, tu te désignais volontaire^^. Le plus simple pour @vdct et le mieux pour OSM peuvent ne pas coïncider. Par contre si `associatedPlace` existe, alors les deux peuvent _peut-être_ coïncider.
Sur [56 078](https://bano.openstreetmap.fr/pifometre/index.html#insee=56078), Le Cap est modélisé façon ~~patachon~~ `addr:housenumber` & `addr:place`, il n'y a pas de rapprochement malgré l’existence d’un `place=hamlet` de ce nom. Villeneuve – Le Cap n’a pas d’adresse dans OSM et son intégration propose de créer une `associatedStreet`.
Le plus simple pour @vdct est _sans doute_ d’ajouter le  `place=*` et de le préciser sur le wiki (après en avoir discuté sur la liste FR), mçeme si dans ce cas `associatedStreet` aurait un nom peu heureux,.
Dans ce cas le nœud du hameau doit avoir le rôle label, histoire de rester homogène avec les modélisations style [boundary](https://www.openstreetmap.org/relation/10060749) des hameaux.

**Comment by deuzeffe** [comment]
Vu que @vdct propose pour les numéros manquants de les intégrer **au choix** par des associatedStreet ou "à l'allemande", je ne saisis pas le hiatus simplicité/efficacité. À moins que la détection soit plus compliquée que la proposition d'intégration ?

Bref, @vdct est seul maître à bord du Pifomètre.

**Comment by vdct** [comment]
Je vais reformuler : pour les adresses attachées à des rues, on avait bien avant BANO la coexistence des schemas point et relation. Pour BANO, on devait donc considérer les 2 modélisations, sinon on passait à côté de pas mal de contenu. Pour Pifomètre, quand il s'est agit d'y proposer des intégrations d'adresses, je n'ai pas imposé un des 2 schémas, j'ai proposé l'intégration avec 2 parfums. C'est discutable, mais je ne voulais pas d'un diktat imposé par un outil.
Pour les adresses des hameaux le point de départ est différent : on n'a pas de schéma basé sur des relations, juste le schema point par point avec addr:place et addr:housenumber. Je ne vois pas l'intérêt d'embrouiller tout le monde en proposant une intégration avec autre chose que ce schéma, via une relation associatedPlace que jamais personne jusque là n'a éprouvé le besoin de créer.

Le souci à venir est ailleurs : c'est le contenu bordélique dès qu'on parle des hameaux. Dans FANTOIR, tous les noms de hameaux ne sont pas qualifiés en lieux-dits, certains noms de voies sont qualifiés en lieux-dits. Idem dans la BAN, cf les cas dans ta commune @deuzeffe . Donc la frontière est floue entre les trucs à ranger dans les onglets 'voie avec adresse' et ceux à placer dans 'lieux-dits' si on propose des adresses à intégrer. Sauf que de l'onglet dépend le style d'intégration : point ou relation si on a la garantie de trouver des voies pour un rôle 'street', ou points isolés + addr:place si on estime qu'on est dans un hameau. Amusez-vous avec ça...

En tout cas c'est bien d'en (re)parler. Je vais essayer de proposer une v1 dans l'été, avec la garantie que ça sera à revoir :D

**Comment by Bibi56** [comment]
@vdct je en sais si tu as progressé sur le sujet, ce que je vois en essayant de résoudre une note : https://bano.openstreetmap.fr/pifometre/#insee=53048&tab=1, cas du lieu-dit L’Hirondelle : propose 

1. une relation (incorrect, car il n’y a pas de rue, ou doit-on modifier le validateur pour tolérer s’il y a un `place` de mème nom dans le coin ?
2. 7 points, mais JOSM n’en récupère aucun).

Un cas particulier ?

N.B. : les numéros affichés au cadastre sont seulement une partie de ces numéros, on dirait un mélange de numérotation métrique et de numérotation classique. Les [notes](https://www.openstreetmap.org/note/3351794#map=16/48.2369/-0.8699&layers=N) correspondent aux numéros classiques, ceux du cadastre.

**Comment by vdct** [comment]
Ce ticket sera inclus dans la branche https://github.com/osm-fr/bano/tree/bano_v3 qui émerge doucement. L'idée est d'y traiter des noms indistinctement, qu'ils soient de voies ou de lieux-dits, et seulement a posteriori d'envoyer vers un modèle rue ou lieu-dit selon la nature des objets OSM portant les noms. Pas encore de code correspondant dans ladite branche mais j'y travaille :)

**Comment by vdct** [comment]
@deuzeffe j'ai l'impression que ce ticket a été traité via la v3 de BANO & Pifomètre, je te laisse clore si oui, ou commenter si non...

**Comment by deuzeffe** [comment]
@vdct c'est bon dans 17 cas sur 19. Considères-tu que c'est un excellent score ? :)

**Comment by vdct** [comment]
Merci ! Allez on ferme :)
