### ISSUE TITLE
FANTOIR T2 2022

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/bano#282]
Hop, il est là : https://data.economie.gouv.fr/api/datasets/1.0/fichier-fantoir-des-voies-et-lieux-dits/attachments/fichier_national_fantoir_situation_juillet_2022_zip/

@vdct je ne sais plus si je dois modifier dans master ou packaging, et avant de faire une bêtise... #NeedHelp

**Comment by vdct** [comment]
Merci merci :)
Pour la branche, packaging est à supprimer. Le mieux c'est que tu créés ta branche en partant de master et que tu proposes ta PR vers master

**Comment by deuzeffe** [comment]
Merci à toi ^^

C'est fait, ici et sur osm-vs-fantoir. Je te laisse contrôler mes bêtises éventuelles !
