### ISSUE TITLE
Mise à jour BANO en cours... qui n'en finit pas

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/bano#284]
Bonjour,

De façon à voir les effets de dégommage de rouge, à partir de Pifomètre je force la màj BANO. Et régulièrement et aléatoirement (par exemple au moment où je rédige ce post), ça mouline dans le vide et je n'ai plus la main.

Une idée d'où vient le problème ?

**Comment by vdct** [comment]
Va falloir investiguer. Est ce toujours sur la même commune ?

**Comment by deuzeffe** [comment]
Non, pas toujours. J'avais par exemple le pb avec cette commune https://bano.openstreetmap.fr/pifometre/index.html#insee=87088&tab=0

Et ce matin, j'ai retenté de forcer la màj, et c'est passé.

C'est aléatoire. Et je ne sais pas quelles sont les infos à transmettre pour un débugage efficace :(

**Comment by deuzeffe** [comment]
À l'instant, pour https://bano.openstreetmap.fr/pifometre/index.html#insee=87064&tab=0

Màj demandée, ça mouline un peu puis le résultat montre que la màj n'est pas faite ?

![Screenshot_20220807_130202](https://user-images.githubusercontent.com/36087963/183287716-c12c1837-2abc-4129-a271-caa2d111d6bf.png)

**Comment by vdct** [comment]
TL;DR : mea culpa
Sur le serveur il y a l'environnement de prod (celui accessible depuis Pifometre) et celui de dev, accessible en console. Normalement les 2 sont mutuellement étanches sauf quand quelqu'un se vautre dans la config et fait des trucs en dev qui interfèrent avec la prod. Et cassent la prod. Ouala. Ahem. D'autres questions ?

**Comment by deuzeffe** [comment]
> TL;DR : mea culpa

Faute avouée, toussa.

> D'autres questions ?

Pas tout de suite.
(je te fais grâce de toutes les répliques ironiques de geek que j'aurais pu écrire ^^)

En conclusion, ça fonctionne nettement mieux !
