### ISSUE TITLE
Fichiers BAN : problème en Finistère (29) et Haute-Loire (43)

### ISSUE THREAD

**Issue by Olyon** [osm-fr/bano#292]
Dans le 43, il n'y a aucune adresse de la BAN.

Le problème existait avant les modifications des derniers jours mais je ne sais pas depuis quand.

**Comment by vdct** [comment]
Corrigé par https://github.com/osm-fr/bano/commit/2c8f99aa41cdbe7457a55b1c809c698a36d32c31
