### ISSUE TITLE
FANTOIR T3 2022

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/bano#303]
Comme les grues, il a migré et il est arrivé ici : https://data.economie.gouv.fr/api/datasets/1.0/fichier-fantoir-des-voies-et-lieux-dits/attachments/fichier_national_fantoir_situation_novembre_2022_zip/

Je m'en occupe ASAP, stay tuned! ;)

Done! 

@vdct je te laisse vérifier/merger...

**Comment by vdct** [comment]
C'est tout mergé, FANTOIR chargé toussa
Merci !
