### ISSUE TITLE
Pourquoi deux bases de données ?

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/bano#325]
Pourquoi les scripts utilisent deux bases de données et non deux schémas postgres dans la même base de données ?

Ça éviterait de devoir gérer deux bases de données, mais également devoir charger certaines données les deux bases.

**Comment by vdct** [comment]
Pour BANO v1 (2014) on n'avait pas de source OSM dédiée au projet, je tapais dans la base qui assurait le rendu (sur layers). Donc tout était organisé avec des appels à une base source distante, et les résultats dans une BD locale. C'est comme ça que c'est parti et je n'ai pas remis ça en question pour la v2 où j'ai monté une BD imposm en local.
Je comprends l'argument de tout rassembler pour s'éviter des copies. L'argument pour garder 2 bases était non technique pour moi, c'était plutôt la tranquillité de pouvoir tout casser d'un côté sans endommager l'autre. Mais ça ne tient pas sur la durée, donc pourquoi pas réunir en effet. Ca demande de se poser un peu pour le nommage et la structure, c'est un chantier qui me semble opportun dans le cadre de la v3 en cours de dev

**Comment by vdct** [comment]
La v3 n'a plus qu'une BD avec un schema osm et un schema public, et c'est beaucoup plus simple en effet
