### ISSUE TITLE
FANTOIR T4 2022 - The last of the century :/

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/bano#337]
C'est le dernier :sob: 

Il est là : https://data.economie.gouv.fr/api/datasets/1.0/fichier-fantoir-des-voies-et-lieux-dits/attachments/fichier_national_fantoir_situation_janvier_2023_zip/

Je mets ma ToDoList à jour. Pour la dernière fois ?

**Comment by deuzeffe** [comment]
@vdct c'est fait. J'ai merdouillé sur la première modif. de load_fantoir.sh mais sans PR. J'ai refais avec PR. Donc, vérifie attentivement ! Et si je dois corriger, dis-le moi !

En ce qui concerne prochain fichier (TOPO), as-tu réussi à scruter ses entrailles ? Et que désires-tu que j'en fasse quand il sera publié (fréquence ?)

**Comment by vdct** [comment]
Et voilà c'est la fin ! Presque émouvant tout ça :wink: 
Merci pour ta veille chaque trimestre qui nous a permis de garder le rythme :+1: 

Concernant TOPO j'ai commencé à m'en occuper dans la (future) [branche v3](https://github.com/osm-fr/bano/tree/bano_v3). C'est pas encore sec. Je ne sais pas quand paraîtra le 1er fichier TOPO (de mémoire c'était mars), ce qui est sûr c'est qu'il y aura un peu de délai avant de l'utiliser dans BANO. Le dernier FANTOIR aura sûrement son trimestre d'utilisation comme ses grands frères. Concernant la fréquence, aussi de mémoire il me semble que TOPO devait être mensuel, mais je ne retrouve plus où je l'ai lu

**Comment by vdct** [comment]
Si TOPO est aussi mal automatisé que l'était FANTOIR, ta veille et ton aide seront toujours autant bienvenues ! Côté compétences j'ai le soupçon que ça devrait bien se passer ;)

**Comment by deuzeffe** [comment]
^^
Première étape : surveiller la première publication du fichier TOPO. https://amicale.net/@opendata est mon ami, tu penses ?
Deuxième étape : scruter le code de BANO v3 et comprendre où mettre à jour. Sinon, faire appel au concepteur du code et à son commentaire du dit code :P
