### ISSUE TITLE
Erreur dans le fichier full.sjson.gz

### ISSUE THREAD

**Issue by ryanfadeau** [osm-fr/bano#344]
J'ai détecté une erreur dans le full.jsson.gz disponible ici: https://bano.openstreetmap.fr/data/

Pour l'adresse à l'id `22093E507T`, dans les `houseNumbers`, il y'a une clé qui est mal formatté qui fait :
- "3 c
c":{}

Il y a comme un saut de ligne, je pense qu'il y a une erreur.

**Comment by vdct** [comment]
Merci pour le signalement. Le souci est présent dans la source BAN sur laquelle s'appuie BANO. J'ai ouvert un ticket côté BAN : https://github.com/BaseAdresseNationale/ban-plateforme/issues/76

**Comment by vdct** [comment]
Tout est rentré dans l'ordre
