### ISSUE TITLE
Erreur nom de commune Marseille fichiers json

### ISSUE THREAD

**Issue by clement-pannetier** [osm-fr/bano#345]
Bonjour,

J'ai remarqué que les adresses recensées dans les fichiers json de la bano sur la commune de Marseille, indiquent uniquement le nom de l'arrondissement dans la clé `city`. Ce n'est par contre pas le cas dans les fichiers csv.

```sh
cat bano-13.json | grep '"city":"Marseille'
cat full.sjson | grep '"city":"Marseille '
```

C'est également le cas via l'outil pifomètre : https://bano.openstreetmap.fr/pifometre/#insee=13201&tab=1 et sur OSM.

Je pense que c'est dû à la configuration des noms de relations, le champ `name` est différent entre ces trois communes : 
- Marseille 1er Arrondissement -> https://www.openstreetmap.org/relation/76091
- Lyon 1er Arrondissement -> https://www.openstreetmap.org/relation/10690
- Paris 1er arrondissement -> https://www.openstreetmap.org/relation/20727

Quelle est donc la bonne façon de procéder, pour mettre à jour les fichiers json, avec le nom complet de la commune de Marseille ?

**Comment by vdct** [comment]
Bonjour,
Les CSV prennent le nom issu du COG, alors que les JSON (et Pifomètre) prennent celui d'OSM. Pour (re)mettre un peu de cohérence il faudrait utiliser le COG côté JSON

**Comment by vdct** [comment]
Les exports CSV et JSON ont été entièrement ré-écrits et les noms de commune à Marseille sont maintenant complets et homogènes entre formats

**Comment by clement-pannetier** [comment]
Bonjour @vdct, le problème avait bien corrigé les noms dans les types street, mais le problème subsiste si l'on recherche par type=city :
- Marseille
```sh
cat full.sjson | grep '"type":"city","name":"1er Arrondissement"'
```
```json
{
  "id": "13201",
  "type": "city",
  "name": "1er Arrondissement",
  "postcode": "13001",
  "lat": 43.300067,
  "lon": 5.382502,
  "city": "1er Arrondissement",
  "departement": "Bouches-du-Rhône",
  "region": "Provence-Alpes-Côte d'Azur",
  "population": 40283,
  "adm_weight": 1,
  "importance": 0.404
}
```

- Paris
```sh
cat full.sjson | grep '"type":"city","name":"Paris 1er Arrondissement"'
```
```json
{
  "id": "75101",
  "type": "city",
  "name": "Paris 1er Arrondissement",
  "postcode": "75001",
  "lat": 48.864614,
  "lon": 2.334396,
  "city": "Paris 1er Arrondissement",
  "departement": "Paris",
  "region": "Île-de-France",
  "population": 16266,
  "adm_weight": 1,
  "importance": 0.3809
}
```

**Comment by vdct** [comment]
bonjour @clement-pannetier 
C'est normalement corrigé, du moins constaté dans le full.sjson.gz de ce matin
