### ISSUE TITLE
Fantoir Avril 2023

### ISSUE THREAD

**Issue by vdct** [osm-fr/bano#352]
cf https://data.economie.gouv.fr/api/datasets/1.0/fichier-fantoir-des-voies-et-lieux-dits/attachments/fichier_national_fantoir_situation_avril_2023_zip/

L'après-dernier FANTOIR ? Ping @deuzeffe :)

**Comment by deuzeffe** [comment]
Mince, j'étais persuadée que le précédent était vraiment le dernier ! Pas pensé à surveiller #MyBad Tu as bien fait de me mentionner @vdct !

Je te fais ça d'ici ce soir, "normalement". Stay tuned!

**Comment by deuzeffe** [comment]
@vdct "normalement", c'est fait. Vérifie si c'est ok :-)

**Comment by vdct** [comment]
Je ne vois pas ta PR ?

**Comment by deuzeffe** [comment]
oublié de cliquer là oukilfo ?
