### ISSUE TITLE
Les multiples localités d'une commune sont exportées sous les mêmes name / city

### ISSUE THREAD

**Issue by ycouble** [osm-fr/bano#354]
Les différentes localités d'une même communes n'ont aucune différence dans le json de sortie de l'export

https://github.com/osm-fr/bano/blob/3f88d5ac7f3bd3cfeb57eaafbeb005fd0c050edd/out/banout-json.sh#LL18C6-L18C6
```
SELECT [...] \"name\": \"' || g.nom || '\" [...] ",\"city\": \"' || g.nom|| '\" [...]
```

Exemple d'une commune (insee: 16054)
```jsonl
{"id":"16054","type":"village", "name":"Le Bouchage", "postcode":"16350", "lat":46.045551, "lon":0.392740, "city":"Le Bouchage", "departement":"Charente", "region":"Nouvelle-Aquitaine", "population":175, "adm_weight":1, "importance":0.2427}
{"id":"16054","type":"village", "name":"Le Bouchage", "postcode":"16350", "lat":46.047581, "lon":0.376958, "city":"Le Bouchage", "departement":"Charente", "region":"Nouvelle-Aquitaine", "population":175, "adm_weight":1, "importance":0.2427}
```

Les points sur les tiles OSM:
![image](https://github.com/osm-fr/bano/assets/4104153/dfeea390-8e60-42d6-8ab7-00f1906f0bb1)

**Comment by ycouble** [comment]
Très proche de https://github.com/osm-fr/bano/issues/345

**Comment by vdct** [comment]
Problème de doublon dans les données, résolu par https://www.openstreetmap.org/changeset/146609042
