### ISSUE TITLE
Remontée arrêt de bus

### ISSUE THREAD

**Issue by gendy54** [osm-fr/bano#363]
Hello,

Je viens de tomber sur une remontée chelou: un arrêt de bus.
https://www.openstreetmap.org/way/1051312292
https://bano.openstreetmap.fr/pifometre_v3/index.html#insee=54404

Il se retrouve dans Pifomètre dans le filtre bleu.

**Comment by vdct** [comment]
Corrigé. Ca sera effectif au fil des màj BANO
