### ISSUE TITLE
Rapprochement non fonctionnel sur pifomètre

### ISSUE THREAD

**Issue by casta** [osm-fr/bano#366]
Bonjour,

J’ai en particulier 2 rues qui me semblent correctement intégrées dans OSM et que je n’arrive pas à rapprocher dans pifomètre… pourtant la rue a bien le code fantoir, et le adresses portées par les numéros de rue concordent bien avec le linéaire.

https://bano.openstreetmap.fr/pifometre/numeros.html?insee=78242&fantoir=782420360&source=BAN&tab=0
https://bano.openstreetmap.fr/pifometre/numeros.html?insee=78242&fantoir=782420179&source=BAN&tab=0

J’ai fais quelque chose de mal, ou bien c’est pifomètre qui a un problème sur ces rues ? J’ai pourtant fait comme toutes les autres rues déjà importées de la commune et de la commune à côté (St-Cyr) qui sont bien rapprochées sans souci…

Merci !

**Comment by vdct** [comment]
Merci pour tes signalements. Pifomètre est ok ici, le problème vient un cran en amont dans la manière de remplir BANO, c'est pour ça que j'ai transféré l'issue. Ca devrait être fixé désormais

**Comment by casta** [comment]
En effet, c’est corrigé !
Super rapide merci.
