### ISSUE TITLE
Communes entières qui passent en blue clair "voie nommée dans OSM mais sans correspondance dans FANTOIR"

### ISSUE THREAD

**Issue by tuxayo** [osm-fr/bano#368]
Au moins depuis le 18 novembre, j'observe ça sur pleins de communes en région PACA, voilà la plus grande que j'ai trouvée:

https://layers.openstreetmap.fr/?zoom=14&lat=43.42355&lon=6.81088&layers=B000000000FFFFFFFFFFFFFFFFFFFFFFFFT

Un endroit où il y en a plein de petites: https://layers.openstreetmap.fr/?zoom=12&lat=43.50068&lon=6.15548&layers=B000000000FFFFFFFFFFFFFFFFFFFFFFFFT

**Comment by vdct** [comment]
La couche BANO de cette page n'est plus mise à jour. Une nouvelle version est en préparation. En attendant je te conseille de basculer sur la page Pifomap de la commune, où le rendu est à jour et maintenu : https://bano.openstreetmap.fr/pifometre/pifomap.html?insee=83118

**Comment by tuxayo** [comment]
Ah cool le problème est connu. Pour l'instant plus de couche chargeable dans  JOSM c'est ça?

Pour travailler à partir de voies_recentes_manquantes, le mieux pour l'instant semble être d'utiliser le lien JOSM et d'ouvrir à côté pifomap.

**Comment by tuxayo** [comment]
> le mieux pour l'instant semble être d'utiliser le lien JOSM et d'ouvrir à côté pifomap.

Cool, la page pifomètre d'une commune a un lien pifomap sur chaque voie donc il n'y a pas à la chercher manuellement. Et ça charge plus vite car c'est zommé sur la voie et pas sur toute la commune :)

**Comment by tuxayo** [comment]
@vdct Est-ce que en attendant je renomme le ticket en "arrêt mise à jour tuiles BANO" et on réouvre ce ticket? Pour que d'autres gens trouvent plus facilement l'info en voyant que le rendu à un problème. Et pour qu'il y en ai un d'ouvert pour suivre des nouvelles sur avoir à nouveau des tuiles BANO.

**Comment by tuxayo** [comment]
Pour compenser, entre temps, la pifomap à une fonction trop bien c'est d'avoir le bouton rapprochement avec une date de données OSM avec laquelle le rapprochement peut être fait. Donc on peut facilement voir si c'est le moment de rapprocher (par rapport à nos derniers changements) et quand c'est le cas c'est rapide et partie BANO de map est mise à jours en directe c'est top! :star_struck: 

Et ça permet de confirmer que les MAJ régulières des données OSM rapprochables marchent toujours. Ça, plus la date du dernière rapprochement automatique donne une bonne idée du délai de MAJ total #361
