### ISSUE TITLE
Liste de postcode pour city et town

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/bano#369]
Dans la sortie JSON pour Addok. 

Les `"type":"city|town"` non pas plusieurs codes postaux quand ils existent alors que les `"type":"place"` ont pour ce cas une liste de postcode.

```json
{"id":"33236","type":"town", "name":"Lège-Cap-Ferret", "postcode":"33950", "lat":44.795105, "lon":-1.147210, "city":"Lège-Cap-Ferret", "departement":"Gironde", "region":"Nouvelle-Aquitaine", "population":8352, "adm_weight":1,}
```

```json
{"id":"33236B015P","citycode":"33236","type":"place","name":"La Forge","postcode":["33950", "33970"],"lat":"44.778236","lon":"-1.162175","city":"Lège-Cap-Ferret","departement":"Gironde","region":"Nouvelle-Aquitaine","importance":0.05}
```

Ça pose problème avec Addok quand on cherche une ville avec un code postal autre que le principal.

**Comment by vdct** [comment]
Merci pour la remontée car je suis pile en train de refondre l'export JSON. Je te dis dès qu'il y a des choses testables pour valider ce point

**Comment by vdct** [comment]
Les exports sont de retour avec une nouvelle version de code sans point commun avec la précédente. Voilà ce que ça donne pour tes exemples :
{"id":"33236","type":"town","name":"Lège-Cap-Ferret","postcode":["33950","33970"],"lat":44.795105,"lon":-1.14721,"city":"Lège-Cap-Ferret","departement":"Gironde","region":"Nouvelle-Aquitaine","population":8352,"adm_weight":1,"importance":0.3631}
{"id":"33236B015","citycode":"33236","type":"street","name":"La Forge","postcode":"33950","lat":44.787859,"lon":-1.153741,"city":"Lège-Cap-Ferret","departement":"Gironde","region":"Nouvelle-Aquitaine","importance":0.0415,"housenumbers":{"29":{"lat":44.788601,"lon":-1.159653}}}
