### ISSUE TITLE
Absence d'une voie sans adresse, mais présente dans la BAN et OSM

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/bano#370]
Dans la sortie JSON Addok il y a des voies sans adresses.
Mais il en manque au moins une qui est bien dans la BAN et dans OSM, mais pas dans la BANO.

> Rue Edgar Degas, Talence

BAN
```json
{"type":"locality","importance":0.51473,"id":"33522_0804","banId":null,"name":"Rue Edgar Degas","postcode":"33400","citycode":["33522"],"oldcitycode":null,"lon":-0.583644,"lat":44.794705,"x":416673.54,"y":6417047.59,"city":["Talence"],"oldcity":null,"context":"33, Gironde, Nouvelle-Aquitaine"}
```

OSM
https://www.openstreetmap.org/way/35172032

**Comment by vdct** [comment]
Le souci viens d'une erreur d'orthographe dans FANTOIR (Edgar**d** Degas) avec un d superflu
Je viens de mettre à jour le way https://www.openstreetmap.org/way/35172032 pour forcer le rapprochement. A noter que le JSON actuel est figé, le fix sera dans le JSON en cours de ré-écriture et basé sur la v3 de BANO

**Comment by frodrigo** [comment]
Ok. Merci.
