### ISSUE TITLE
Fréquence des exports CSV

### ISSUE THREAD

**Issue by adrienandrem** [osm-fr/bano#371]
Bonjour,

il me semblait que [les exports CSV](https://bano.openstreetmap.fr/data) étaient générés tous les jours ou au moins une fois par semaine.

Je vois que les fichiers proposés datent de novembre dernier, est-ce normal ? Quelle est la fréquence de mise à jour ?

**Comment by vdct** [comment]
La fréquence normale est toutes les 24h, tu n'as pas rêvé. Depuis quelques semaines je finalise la nouvelle version des exports, qui vise à remplacer le flux actuel, sans changer le format ni la fréquence, et qui s'appuie sur la dernière version de BANO (la v3, celle qui alimente Pifomètre). J'avais préventivement débranché la màj nocturne de la V2 (la "vieille" version) car elle manque de maintenance et commençait à diffuser du contenu parfois tronqué. Le fait est que je visais la fin 2023 pour publier la nouvelle version et que je tarde. Les exports CSV devraient arriver sous quinzaine, suivront le JSON et les autres formats.
Merci pour ta patience

**Comment by vdct** [comment]
La fréquence est à nouveau quotidienne (autour de 2-3h du matin UTC). Tous les formats sont exportés par département, ainsi qu'un CSV et un JSON France. Merci d'ouvrir un ticket pour toute anomalie que tu relèverais (format, doublons...)
