### ISSUE TITLE
Exports CSV plus vieux que leurs équivalents JSON

### ISSUE THREAD

**Issue by adrienandrem** [osm-fr/bano#373]
Bonjour,

je remarque que certains CSV plus vieux que leurs équivalents JSON.
Comme [ici](https://bano.openstreetmap.fr/data/) :
```
bano-971.csv	2024-01-18 02:56
bano-971.json.gz	2024-01-19 02:46
```

**Comment by vdct** [comment]
Merci pour ton signalement. 
En fait les 2 fichiers sont du 18/01. Le 19/01 les exports se sont bien passés pour les départements de 01 à 82 et ont échoué à partir du 83, laissant en place les fichiers du 18. Mais le zip des versions autres que CSV a bien eu lieu le 19 pour tous les départements, dont les dates visibles sont trompeuses ici. Je n'ai rien dans les logs pour expliquer le pourquoi de l'échec des exports le 19 pour les départements > 83. J'imagine un souci de mémoire en cas de conflit de ressources. Il va falloir surveiller dans les jours à venir.

**Comment by vdct** [comment]
retour à la normale ce matin

![image](https://github.com/osm-fr/bano/assets/2237260/fc78fdbb-81ec-487d-9a5f-2bea33c96a24)
