### ISSUE TITLE
"Petit Chemin Pt Chem" et variantes

### ISSUE THREAD

**Issue by Art-Penteur** [osm-fr/bano#38]
On trouve encore des ;
"Petit Chemin Pt Chem" : 
http://layers.openstreetmap.fr/?zoom=19&lat=43.60568&lon=1.32948&layers=0B000FFFFFFFFFFFFFFFFFFFFFFT

"Petit Chemin Petit Chem" : 
http://layers.openstreetmap.fr/?zoom=18&lat=43.61335&lon=1.3292&layers=0B000FFFFFFFFFFFFFFFFFFFFFFT

"Petite Allée Pte Allée" : 
http://layers.openstreetmap.fr/?zoom=19&lat=43.6031&lon=1.34732&layers=0B000FFFFFFFFFFFFFFFFFFFFFFT

"Petite Allée Pte All" : 
http://layers.openstreetmap.fr/?zoom=18&lat=43.60568&lon=1.34353&layers=0B000FFFFFFFFFFFFFFFFFFFFFFT

**Comment by cquest** [comment]
060881050P -> Petite Avenue  / Pet Ave
