### ISSUE TITLE
Ou trouve ton le fichie à importer TOPO20211101.gz

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/bano#385]
Ou trouve ton le fichier à importer TOPO20211101.gz ?

**Comment by vdct** [comment]
C'est un fichier de test fourni par la DGFiP au début du remplacement de FANTOIR par TOPO. TOPO a finalement mis des siècles à émerger et c'est enfin disponible depuis quelsues mois. Dernière version : https://www.data.gouv.fr/fr/datasets/fichier-des-entites-topographiques-decembre-2023/
Je suis ces jours-ci enfin en train de basculer du fichier de test aux releases +- mensuelles de TOPO, ça sera bientôt dispo

**Comment by frodrigo** [comment]
Ok, merci.

**Comment by vdct** [comment]
@frodrigo pour info le changement est fait via https://github.com/osm-fr/bano/commit/75660e12c01189c8fcbfb54492d7cea01ca133bf

**Comment by frodrigo** [comment]
Merci. Oui j'ai vu après rebase que le téléchargement était bien long !
