### ISSUE TITLE
Non reproductibilité - Absence des lieux dit en sortie - Manque lieux_dits_post_process.sql dans git

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/bano#393]
En exécutant le projet en local, je n'ai pas le même résultat que les données BANO publiées.
Il manque les lieux-dit venant du cadastre. Le processus les charge bien en base de données. Mais je n'ai pas ensuite vu de partie du code qui les utilise.

Par contre suite au chargement des lieux-dit depuis le cadastre un script SQL optionnel est exécuté : `lieux_dits_post_process.sql`. Mais ce script n'est pas le dépôt git.

**Comment by vdct** [comment]
le process de chargement est `bano charge_ld_cadastre`
il remplit la table lieux_dits
cette table est ensuite interrogée à l'occasion de chaque invocation de `bano rapprochement` via la requete charge_points_nommes_lieux-dits_CADASTRE (via https://github.com/osm-fr/bano/blob/bano_v3/bano/rapprochement.py#L24)

Par ailleurs le script lieux_dits_post_process est un héritage de la v2 et doit être supprimé, merci pour le signalement

**Comment by frodrigo** [comment]
En refaisant tout le process c'est bon cette fois. Je n'avais pas du tout faire dans le bon ordre. Merci.
