### ISSUE TITLE
problème de rapprochement

### ISSUE THREAD

**Issue by Olyon** [osm-fr/bano#404]
Il y a des communes comme ici [Neuvéglise-sur-Truyère](https://bano.openstreetmap.fr/pifometre/index.html?insee=15142) où le rapprochement ne se fait pas. Il y a une ligne pour la rue BAN/Topo et une autre OSM alors que le nom est le même.

**Comment by vdct** [comment]
Ca fait plusieurs fois que je vois des communes fusionnées avec ce genre de défaut. Je suis en train de refondre le processus de rapprochement, et clairement il y a un truc à réparer pour les communes fusionnées. Merci pour le signalement

**Comment by vdct** [comment]
@Olyon j'ai réparé un mécanisme de rapprochement propre aux communes fusionnées hier. Si tu peux regarder le résultat sur les cas que tu avais reoéré ? Merci

**Comment by Olyon** [comment]
Le problème a disparu ! merci
