### ISSUE TITLE
points adresse de deux rues fusionnés dans une seule rue

### ISSUE THREAD

**Issue by zorglubu** [osm-fr/bano#407]
Bonjour,
Je ne sais pas si le problème vient de pifomètre ou de la BAN (ou d'ailleurs) donc je le signale à tout hasard. Je l'ai rencontré sur plusieurs communes.
Le mieux est de partir d'un [exemple](https://bano.openstreetmap.fr/pifometre/index.html?insee=23239), en triant sur la colonne _Intégrer les adresses_.

Dans cette page de nombreuses voies (sans code Fantoir) apparaissent non seulement deux fois, mais elles vont en général par paires qui ont été fusionnées.
Exemple la _Route des Grands Gouttes_ affiche les mêmes points adresse que l'_Impasse des Carrières_.
Idem pour l'_Allée des Champs_ et la _Route des Châtaigners_.

**Comment by vdct** [comment]
Merci du signalement @zorglubu , encore un joli bug :+1: 
Ca devrait être corrigé à partir de maintenant, je te laisse vérifier

**Comment by zorglubu** [comment]
Ça me semble tout bon maintenant. Merci.
