### ISSUE TITLE
Numéro indiqué comme non intégré car maison en limite de commune

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/bano#408]
Le numéro 3 de la Rue de l'Abbé François Pierre n'est pas considéré comme intégré, car la maison est sur la commune de Vantoux
https://bano.openstreetmap.fr/pifometre/numeros.html?insee=57463&fantoir=574630051&source=BAN&tab=0

**Comment by vdct** [comment]
En effet le numéro reste orphelin. Pour le rattacher à la commune il faudrait que la relation associatedStreet comporte un code FANTOIR (574630051) pour expliciter que tout ce qui s'y rattache est bien associé à une seule commune, et ce indépendamment de l'implantation dans ou en dehors de la commune

**Comment by Jean-BaptisteC** [comment]
Est ce que pifomètre serait en mesure de détecter des numéros en dehors des limites de commune ?

**Comment by vdct** [comment]
C'est déjà le cas, mais uniquement pour les numéros rattachés à une relation associatedStreet comportant un code FANTOIR rattaché à la commune. On a un lien sémantique à défaut de lien spatial d'inclusion

**Comment by Jean-BaptisteC** [comment]
Et pour les rues sans fantoir ?😁

**Comment by vdct** [comment]
Je n'ai pas de solution dans ce cas pour ne pas basculer dans une usine à gaz
