### ISSUE TITLE
Numéro d'adresse sur un multipolygone non vu comme mappé par pifomètre

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/bano#409]
https://bano.openstreetmap.fr/pifometre/numeros.html?insee=57463&fantoir=574636505&source=BAN&tab=0

Le numéro 207 de cette rue est considérée comme absent d'osm alors que le numéro est bien présent sur le multipolygone https://www.openstreetmap.org/relation/13671007#map=19/49.10474/6.21115

**Comment by vdct** [comment]
Merci pour le signalement :+1: 
Ca devrait être corrigé par la màj de cette nuit
