### ISSUE TITLE
Mots collés

### ISSUE THREAD

**Issue by vdct** [osm-fr/bano#41]
Ce ticket vise à recenser les mots abusivement collés dans le cadastre. Merci d'indiquer un lien vers le rendu Bano.

Oradour-Surglane -> Oradour-sur-Glane
http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#19/48.09615/-1.65901

**Comment by djoman** [comment]
bonjour,
http://cadastre.openstreetmap.fr/fantoir/#insee=44050
sur ce premier onglet toute cette liste à des noms de lieux-dits collés. 
http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#15/47.4008/-2.1389
djoman

**Comment by vdct** [comment]
@djoman les cas que tu indiques sont plus en lien avec ce ticket : https://github.com/osm-fr/bano/issues/10 . Ils ne sont pas traités comme suffixes faute d'une fréquence suffisante : en l'état, il faut trouver un même terme dans 5 voies d'une commune pour décider que c'est un suffixe.
Pour Crossac, le rapprochement entre les voies d'OSM et du Cadastre/Fantoir ne pourra se faire qu'avec le tag ref:FR:FANTOIR pour les quelques rues concernées.

**Comment by djoman** [comment]
bonjour
    ok pour le #10
    mais toutes ces tronçons ont déjà le ref:FR:FANTOIR depuis 3 mois
    c'est pour cela que j'ai cru que c'était encore le même problème.
    djoman
    
    
    Le 04/02/2015 22:23, vdct a écrit :
    
    
      @djoman les cas que tu indiques sont
        plus en lien avec ce ticket : #10
        . Ils ne sont pas traités comme suffixes faute d'une fréquence
        suffisante : en l'état, il faut trouver un même terme dans 5
        voies d'une commune pour décider que c'est un suffixe.
        Pour Crossac, le rapprochement entre les voies d'OSM et du
        Cadastre/Fantoir ne pourra se faire qu'avec le tag
        ref:FR:FANTOIR pour les quelques rues concernées.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by vdct** [comment]
Oops je vois les codes Fantoir en effet. On est donc dans un cas (particulier à Crossac ?) qui fait l'objet d'un autre ticket : https://github.com/osm-fr/bano/issues/71 non encore traité (et pas trivial).

**Comment by PiRK** [comment]
"Jean-Jacquesrousseau" -> "Jean-Jacques Rousseau" : http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#20/45.19128/5.72919
