### ISSUE TITLE
Adresse remplacée par une autre

### ISSUE THREAD

**Issue by clement-pannetier** [osm-fr/bano#415]
Bonjour,

La rue "Rue Édouard Vaillant 37000 Tours" ne remonte pas dans le fichier full.sjson, elle est remplacée par la "Place du Général Leclerc 37000 Tours" :
```shell
cat full.sjson | grep 372611620
```
```json
{
  "id": "372611620",
  "citycode": "37261",
  "type": "street",
  "name": "Place du Général Leclerc",
  "postcode": "37000",
  "lat": 47.383224,
  "lon": 0.702935,
  "city": "Tours",
  "departement": "Indre-et-Loire",
  "region": "Centre-Val de Loire",
  "importance": 0.6564,
  "housenumbers": {
    [...]
  }
}
```

J'ai tenté de corriger dans OSM, sans succès : https://www.openstreetmap.org/changeset/153264530

Pouvez-vous regarder d'où vient le problème ?

**Comment by vdct** [comment]
bonsoir @clement-pannetier 
je pense que votre fix a fonctionné car je ne constate plus le souci avec le dump de la nuit dernière. Et ça me paraît cohérent car vous avez supprimé de la relation les membres ajoutés par erreur avec le nom "Place du Général Leclerc"

**Comment by clement-pannetier** [comment]
Bonjour @vdct, en effet je ne constate plus le soucis, je clos la demande, merci :+1:
