### ISSUE TITLE
Addresses à Vezin-le-Coquet absentes des fichiers json

### ISSUE THREAD

**Issue by clement-pannetier** [osm-fr/bano#424]
Bonjour, les adresses de la commune de Vezin-le-Coquet sont absentes des fichiers json (full.sjson et bano-35.json).

```
cat bano-35.json | grep Vezin-le-Coquet
cat full.sjson | grep 353530023
```

L'adresse recherchée était celle-ci :
![image](https://github.com/user-attachments/assets/40d69372-3915-4af6-94cf-7e5fe9050eab)

**Comment by vdct** [comment]
Bonsoir
ça devrait se corriger dans les fichiers du 7/9. Le souci vient d'une suppression erronée de données, corrigée via https://www.openstreetmap.org/changeset/156249767
