### ISSUE TITLE
Nom de la voie non visible sur la page qualification des adresses

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/bano#426]
Le nom de la voie n'est pas visible en haut de la page
Exemple: https://bano.openstreetmap.fr/pifometre/numeros.html?insee=88367&fantoir=883670450&source=BAN&tab=0

**Comment by gendy54** [comment]
Quand je clique sur ton lien, je n'ai pas de problème. Mets une capture d'écran pour qu'on comprenne mieux.

**Comment by Jean-BaptisteC** [comment]
Je n'ai plus le problème :)
Surement un problème de rafraichissement

**Comment by Khomille** [comment]
C'est retombé en marche apparemment. Mais ça a l'air aléatoire. Il y a en effet un problème de voies au nom vide qu'il faudra régler sérieusement. On peut laisser le ticket ouvert.

**Comment by vdct** [comment]
C'est corrigé
