### ISSUE TITLE
Problème des stats par département

### ISSUE THREAD

**Issue by Olyon** [osm-fr/bano#427]
Dans 
https://github.com/osm-fr/bano/blob/bano_v3/bano/sql/stats_departementales.sql
on a :
nb_voies_ban_rapprochees
AS
(SELECT dep, count(*) AS nb_voies_ban_rapprochees
FROM (SELECT code_dept AS dep, fantoir FROM bano_adresses WHERE source = 'OSM'
     INTERSECT
	 SELECT code_dept, fantoir FROM bano_adresses WHERE source = 'BAN')a
GROUP BY 1),

On obtient comme voies rapprochées que celles qui ont des adresses dans OSM en oubliant les voies nommées sans adresses, non ?

**Comment by vdct** [comment]
Oui c'est ça. C'était l'objet du fix https://github.com/osm-fr/bano/commit/748903f50acdcf918138ca669ebc7bb5c0b3e0c1 
Ça devrait être ok maintenant
