### ISSUE TITLE
Orthographe variable entre releases

### ISSUE THREAD

**Issue by vdct** [osm-fr/bano#49]
Certaines rues ont des portions avec des variations de noms :+1: http://www.openstreetmap.org/way/296782371
http://www.openstreetmap.org/way/296782373

 Côté Bano ça n'est pas toujours le même nom qui est retenu, ce qui occasionne des lignes de diff sans intérêt :
https://github.com/osm-fr/bano-data/commit/53dfcbdbabe78bd8069aef8aff5bd7efde5f0ada#diff-9bb497eb39fc2e45ce50576a3e66251eL25017

=> Ajouter un tri dans la récupération des données OSM pour gagner en régularité.
Clés de tri possible : ordre alphabétique sur le nom, ou nom porté par la plus grande longueur de voie

**Comment by Bibi56** [comment]
Ceci dit, sur cet exemple, un contributeur a résolu le problème en ajoutant l'accent.

**Comment by vdct** [comment]
bano-data n'est plus utilisé par ailleurs
