### ISSUE TITLE
Intégrer les lieux-dits

### ISSUE THREAD

**Issue by vdct** [osm-fr/bano#50]
Les lieux-dits sont un support d'adresse en zone rurale. Ils sont absents de Bano jusque là.
- intégrer les lieux-dits issus d'OSM (node + tag place=\* + name=*)
- intégrer les noms des parcelles du Cadastre là où il n'y a pas d'adressage au n°
- améliorer la localisation du ponctuel portant ces noms en fonction de la situation de bâtiments (idéalement hors bâti léger) inclus dans les parcelles couvertes par un même nom dans une commune donnée
- pour les 2 sources (Cadastre et OSM) tenter un rapprochement avec les noms de lieux présents dans FANTOIR
- proposer via un export dédié la couche de ponctuels issue du mix de sources, a priori en privilégiant le X,Y et l'orthographe des ponctuels présents dans OSM

**Comment by julien-noblet** [comment]
Salut,

un petit "pré" traitement serait de prendre les *nœuds* et *bâti* contenant les tags:
**addr:place** et **addr:housenumber** cela ne résoudra pas tout mais permettra au moins d’intégrer les hameaux qui ont un numéro de renseigné dans OSM.

Je contourne un peu le truc mais il me semble qu'en France, que l'on soit rattaché à une voie ou à un lieu-dit, on a un numéro que la mairie doit nous communiquer...

**Comment by vdct** [comment]
à considérer dans la prise en compte des noms de parcelles : 
- on trouve des blocs de parcelles homonymes à différents endroits d'une même commune
=> comparer la localisation des nodes place=* en tolérant qu'ils soient en dehors de l'emprise des parcelles de même nom. La distance à tolérer est à déterminer.
- en première approche, ne pas considérer les parcelles pour lesquelles on dispose d'un numéro, ni celles sans numéro, mais dont le nom de voie existe ailleurs associé à un numéro
