### ISSUE TITLE
Integration de BANO dans Nominatim

### ISSUE THREAD

**Issue by mr1azl** [osm-fr/bano#60]
J'ai installé mon propre serveur Nominatim en suivant [ ce guide](http://wiki.openstreetmap.org/wiki/Nominatim/Installation).

Y a-t-il un moyen de mettre à jour ma base en utilisant les fichiers de BANO ?

**Comment by pascalheraud** [comment]
Rien à ce sujet depuis 2014 ? Même pour BAN ? :)

**Comment by vdct** [comment]
La question est pour Nominatim
