### ISSUE TITLE
"Rue Léon Blum, Liévin" positionné à Loos-en-Gohelle

### ISSUE THREAD

**Issue by yohanboniface** [osm-fr/bano#69]
Ref:
```
625102151U||Rue Léon Blum|62800|Liévin|OSM|50.444242|2.787137|Pas-de-Calais|Nord-Pas-de-Calais|street
```
Voici le positionnement sur une carte:
![screenshot from 2014-11-10 11 07 50](https://cloud.githubusercontent.com/assets/146023/4974252/ff1f9718-68c9-11e4-9ed9-6c692db07b34.png)
Alors qu'il y a bien une "rue Léon Blum" à Liévin:
![selection_006](https://cloud.githubusercontent.com/assets/146023/4974278/5593fa94-68ca-11e4-8c65-30c547d1df28.png)

**Comment by vdct** [comment]
Le commit https://github.com/osm-fr/bano/commit/d6f9e7b36957cec4d6769c00d7cbd78172427861 vise à ne considérer que les voies incluses dans la commune, lorsque on ratisse à la fois des voies homonymes dans et en dehors de la commune, du fait du partage de géométrie (via au moins 1 point) entre les voies des communes limitrophes et la limite de la commune traitée (le cas initial du ticket).

**Comment by vdct** [comment]
![screenshot - 11122015 - 21 31 18](https://cloud.githubusercontent.com/assets/2237260/11754894/b586e67a-a04e-11e5-8492-2e501dd2efab.png)
Le point tombe maintenant en début de la bonne voie

**Comment by yohanboniface** [comment]
Cool, merci :)
