### ISSUE TITLE
Repérer les voies tracées grossièrement via les adresses BANO

### ISSUE THREAD

**Issue by GeorgeKaplan** [osm-fr/bano#80]
Voici une idée d'amélioration de la géométrie des voies : repérer les voies où les adresses paires et impaires sont du même côté de la voie et les signaler en tant qu'erreurs Osmose. Le contributeur peut ensuite vérifier avec l'imagerie aérienne et corriger la voie au besoin.

Exemple à Jouy en Josas (je laisse volontairement les erreurs de géométrie ) : http://layers.openstreetmap.fr/?zoom=17&lat=48.77554&lon=2.16468&layers=B0000FFFFFFFFFFFFFFFFFFFFFT

Autre cas : des adresses que d'un seul côté (pair ou impair) qui passent de l'autre côté de la voie quand on les suit dans l'ordre. Exemple rue Juliette Drouet : http://layers.openstreetmap.fr/?zoom=18&lat=48.77188&lon=2.16664&layers=B0000FFFFFFFFFFFFFFFFFFFFFT

**Comment by vdct** [comment]
Idée à creuser, mais pas du côté BANO. Voir peut-être vers OSMOSE ?
