### ISSUE TITLE
Pas de conversion de RTE en Route pour des communes nouvellement vectorisées

### ISSUE THREAD

**Issue by GeorgeKaplan** [osm-fr/bano#82]
http://layers.openstreetmap.fr/?zoom=14&lat=49.81307&lon=1.10998&layers=B0000FFFFFFFFFFFFFFFFFFFFFT

A Crosville-sur-scie, Dénestanville, La Chaussée, 3 communes nouvellement vectorisées (https://twitter.com/CadInfos/status/540378145728528384 ), le rendu affiche les noms de rue en mode "Minitel".
Ex : IMP DES AUBEPINES
RTE DES BEGONIAS

La commune de Sainte-Foy toute proche ne présente pas ce problème (cadastre du 23 oct).

**Comment by vdct** [comment]
J'ai rejoué l'import des plans cadastraux des 3 communes, c'est résolu désormais. Merci George.
