### ISSUE TITLE
Présence de | dans les libellés de voies rapprochés...

### ISSUE THREAD

**Issue by cquest** [osm-fr/bano#84]
Exemple: 351150070M -> Rue Alexandre |||
Deux autres cas sur 94056 
 PL DU GEN DE GAULLE | RUE DE SERVON 
et
RUE DE SERVON | PL DU GEN DE GAULLE

**Comment by cquest** [comment]
Mais aussi dans les numéros ;)

030952010M-2|24

**Comment by vdct** [comment]
@cquest Un pb de données OSM, non ? Je ne retrouve pas les cas sur 94056

**Comment by vdct** [comment]
Ménage fait dans les données : 
http://www.openstreetmap.org/changeset/35893258
https://www.openstreetmap.org/changeset/35893593
