### ISSUE TITLE
Rapprochement sur les landuse=residential

### ISSUE THREAD

**Issue by vdct** [osm-fr/bano#86]
Permettre ce rapprochement même sans ref:FR:FANTOIR

**Comment by JBosm** [comment]
C'est vraiment une bonne idée, ça ? Ça fait partie des bonnes pratiques de contribution ?

**Comment by vdct** [comment]
C'est surtout pour rapprocher les résidences & lotissements. J'aimerais un schéma plus précis que landuse=residential + name=* mais c'est un sujet sans conclusion jusque là...
