### ISSUE TITLE
De l'accentuation des voies dans la BAN(O) - un cas 

### ISSUE THREAD

**Issue by parville** [osm-fr/bano#89]
Bonjour,

En téléchargeant la bano-76.shp j'ai constaté que le premier libellé d'adresse proposait dans la commune de code insee 76001  (Allouville Bellefosse) "Allée Abbe du Détroit".

Je ne m'explique pas le "Détroit" accentué versus l' "Abbe" non accentué ?!

Nota : il n'y a pas de rapprochement automatique avec OSM car OSM parle de la "Rue Abbé du Détroit"

Cordialement
HP

**Comment by vdct** [comment]
Le libellé livré dans le shp ne vient pas d'OSM mais du Cadastre, où l'accentuation est plus hasardeuse. On ne prend pas le libellé OSM car en effet il n'a pas été rapproché. En cause, le type de voie : "Allée" pour le Fantoir, "Rue" pour OSM : différence suffisante pour ne pas apparier les deux. Si le libellé avec Rue est le bon, alors il faudrait explicitement lui ajouter le code Fantoir dans OSM, avec le tag ref:FR:FANTOIR=760010007F, et à partir de là, le libellé de la voie dans les expots BANO sera "Rue Abbé du Détroit". À noter que le plan cadastral parle de la "Rue de l'Abbé du Détroit".

**Comment by tyndare** [comment]
Le nom de la rue viens du fichier FANTOIR qui ne contient aucun accent. Pour rajouter les accents on cherche les mots accentués dessinés sur le cadastre. Sur le cadastre il y a le mot "l'Abbé" qui n'a pas été rapproché avec "Abbe". J'ai rajouté un filtre pour découper les mots à l'apostrophe:

https://github.com/osm-fr/bano/commit/fd8a590791dde1bd1749709d374d451375d5e1ea

**Comment by vdct** [comment]
Merci Tyndare. Code répercuté dans BANO, j'ai rejoué l'import d'Allouville Bellefosse et on a maintenant "Allée Abbé du Détroit" pour 7 adresses. Attention cependant : ce code n'est pas rétroactif, il va avant tout profiter à l'import des nouvelles communes vectorielles. Pour qu'il profite aux anciennes, vu les changements récents dans la charte graphique des plans du cadastre, il faudrait reconstituer le cache de tous les PDFs des 31.000 communes avec cette nouvelle charte.

**Comment by tyndare** [comment]
Il faudrait tester pour être sur mais en théorie les changements pour lire la nouvelle police de caractère des PDFs n'annulent pas la capacité de lire les anciens PDFs. Pour les limites c'était un changement des fichiers XML mais là aussi le code devrais continuer a pouvoir lire l'ancien format.

**Comment by parville** [comment]
Excellent. 
J'avais volontairement rejeté l'idée de forcer le rapprochement avec OSM car c'est bien l'étrangeté du libellé à moitié accentué qu'il me paraissait intéressant de traiter, ce que vous avez fait avec brio !

**Comment by vdct** [comment]
@tyndare : bon à savoir, merci. Il va falloir tester sur qq communes, et ensuite, une passe complète.

**Comment by vdct** [comment]
Le cache complet a été reconstitué courant septembre
