### ISSUE TITLE
rapprochement de nom de voie sans voie dans osm

### ISSUE THREAD

**Issue by didier2020** [osm-fr/bano#91]
j'ai trouvé des imports d'adresse , que des nodes (addr:housenumber et addr:street) dont le addr:street etait la copie conforme de fantoir (tout en majuscule). Dans osm les voies n'existaient pas ou n'avait pas de tag name.
ce qui donne des choses bizarres:
http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#18/48.13446/-0.43149
=> du vert, du bleu et du rouge
http://cadastre.openstreetmap.fr/fantoir/#insee=53065
tout est rapproché !

on peut les quantifier
select count(*)  from planet_osm_point
 where (upper("addr:street")="addr:street" and "addr:street" ~ E'[A-Z '']{6,}'

**Comment by vdct** [comment]
Par rapport à BANO ça ne pose pas de problème. Après, c'est très regretable (pour rester poli) d'un point de vue OSM. Donc on ne fera pas grand chose dans le code de BANO pour ça, en revanche une analyse Osmose pour détecter la situation aurait du sens.
