### ISSUE TITLE
Parc des Buttes-Chaumont non rapproché

### ISSUE THREAD

**Issue by bricemallet** [osm-fr/bano#94]
Le Parc des Buttes-Chaumont apparaît toujours en rouge dans http://layers.openstreetmap.fr/?zoom=17&lat=48.87877&lon=2.38085&layers=B0000FFFFFFFFFFFFFFFFFFFFFT alors même que ce leisure=park (173204460) est affublé d'un ref:FR:FANTOIR=751191395R depuis le 23/08/14 par un certain cquest !
Le code Fantoir est il compatible avec park ?

**Comment by vdct** [comment]
La recherche des noms et codes Fantoir sur les surfaces n'était pas à niveau sur les communes dites "à suffixes" (voir https://github.com/osm-fr/bano/issues/10). Elles sont maintenant à niveau, mais dans le même temps Paris 19 n'est plus une commune à suffixe, car le seul détecté ('19') est considéré comme non significatif.
