### ISSUE TITLE
Rues non rapprochées

### ISSUE THREAD

**Issue by bricemallet** [osm-fr/bano#95]
Cas de figure discuté vendredi lors réunion parisienne, deux rues apparaissent en rouge sur rendu carto, cf. http://layers.openstreetmap.fr/?zoom=17&lat=48.87877&lon=2.38085& :
- rue Philippe Hecht
- Rue Barrelet de Ricou

alors même qu'elles sont toutes deux dans le tableau des "355 voies FANTOIR avec rapprochement OSM" (http://cadastre.openstreetmap.fr/fantoir/#insee=75119) et ce depuis un certain temps déjà.

**Comment by vdct** [comment]
Ces rues étaient impactées par la présence d'un suffixe '19' dans des voies à proximité, qui perturbait le rapprochement. Les suffixes (https://github.com/osm-fr/bano/issues/10) purement numériques (la majorité à Paris) sont maintenant ignorés.

**Comment by bricemallet** [comment]
N'apparaissent plus en rouge sur rendu BANO en effet : merci.
