### ISSUE TITLE
Collision des erreurs de rapprochement BAN et OSM sur le rendu 

### ISSUE THREAD

**Issue by bagage** [osm-fr/bano#98]
Voir par exemple [ici](http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#19/45.16046/5.33148), l'erreur de rapprochement BAN (en italique) et celle de rapprochement OSM (en regular) se chevauchent, et ce pour à peu prés tous les niveaux de zoom.

Si les 2 labels sont positionnés relativement à leur origine de la même façon (sud est a priori ?), est-ce qu'il serait possible de changer l'un des deux positionnements pour éviter le chevauchement ?

**Comment by cquest** [comment]
Le nom de voie issu de la BAN est désormais décalé vers le haut (et celui de BANO vers le bas)
https://github.com/osm-fr/bano-cartocss/commit/2833d55ac6c3dfe1aacf03657e1843e1312ade15
