### ISSUE TITLE
fichiers exportés incomplets

### ISSUE THREAD

**Issue by Cactusbone** [osm-fr/bano#99]
(je le remet ici depuis la mailing list)

Le fichier full.sjson.gz sur http://bano.openstreetmap.fr/data/ fait 33k et correspond à "La réunion", et plein de petites tailles sur plusieurs fichiers. 
bano-76.csv par exemple est vide. 
bano-75.json.gz fait 33 octets, ça fait un peut léger pour Paris , même en compressant comme des malades :D 

un soucis d'import cette nuit ?

**Comment by Cactusbone** [comment]
c'est bon ! :) merci ;)

**Comment by Cactusbone** [comment]
ça le refait ! (visiblement depuis le 28 octobre)
full.sjson.gz fait 16Mo avec plein de départements a 34 octets

**Comment by cquest** [comment]
Effectivement ça a coincé par exemple le 8/12 pour les départements 63 à 76... je regarde ça dès que possible (pas trop connecté en ce moment car en congés).

**Comment by cquest** [comment]
J'ai fait quelques corrections pour l'export. Il y a encore des problèmes de performances que je dois régler... et on a aussi eu un pépin de disque plein qui a sûrement été à l'origine des fichiers incomplets.

**Comment by Cactusbone** [comment]
ouais c'est beaucoup mieux ! :+1: 
on peux faire un test auto quelque part pour surveiller ?

**Comment by cquest** [comment]
J'ai encore revu le script avec pas mal d'optimisations ainsi qu'une correction (certaines adresses sortaient plusieurs fois, ce qui ne gène pas addok à l'import mais n'est pas très propre).
C'est donc en principe réglé.
